/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDate;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetCorporationCorporationIdMiningObservers200Ok.JSON_PROPERTY_LAST_UPDATED,
  GetCorporationCorporationIdMiningObservers200Ok.JSON_PROPERTY_OBSERVER_ID,
  GetCorporationCorporationIdMiningObservers200Ok.JSON_PROPERTY_OBSERVER_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCorporationCorporationIdMiningObservers200Ok implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LAST_UPDATED = "last_updated";
  private LocalDate lastUpdated;

  public static final String JSON_PROPERTY_OBSERVER_ID = "observer_id";
  private Long observerId;

  /**
   * The category of the observing entity
   */
  public enum ObserverTypeEnum {
    STRUCTURE("structure");

    private String value;

    ObserverTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObserverTypeEnum fromValue(String value) {
      for (ObserverTypeEnum b : ObserverTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBSERVER_TYPE = "observer_type";
  private ObserverTypeEnum observerType;


  public GetCorporationCorporationIdMiningObservers200Ok lastUpdated(LocalDate lastUpdated) {
    
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * last_updated string
   * @return lastUpdated
  **/
  @ApiModelProperty(required = true, value = "last_updated string")
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getLastUpdated() {
    return lastUpdated;
  }


  public void setLastUpdated(LocalDate lastUpdated) {
    this.lastUpdated = lastUpdated;
  }


  public GetCorporationCorporationIdMiningObservers200Ok observerId(Long observerId) {
    
    this.observerId = observerId;
    return this;
  }

   /**
   * The entity that was observing the asteroid field when it was mined. 
   * @return observerId
  **/
  @ApiModelProperty(required = true, value = "The entity that was observing the asteroid field when it was mined. ")
  @JsonProperty(JSON_PROPERTY_OBSERVER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getObserverId() {
    return observerId;
  }


  public void setObserverId(Long observerId) {
    this.observerId = observerId;
  }


  public GetCorporationCorporationIdMiningObservers200Ok observerType(ObserverTypeEnum observerType) {
    
    this.observerType = observerType;
    return this;
  }

   /**
   * The category of the observing entity
   * @return observerType
  **/
  @ApiModelProperty(required = true, value = "The category of the observing entity")
  @JsonProperty(JSON_PROPERTY_OBSERVER_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ObserverTypeEnum getObserverType() {
    return observerType;
  }


  public void setObserverType(ObserverTypeEnum observerType) {
    this.observerType = observerType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationCorporationIdMiningObservers200Ok getCorporationCorporationIdMiningObservers200Ok = (GetCorporationCorporationIdMiningObservers200Ok) o;
    return Objects.equals(this.lastUpdated, getCorporationCorporationIdMiningObservers200Ok.lastUpdated) &&
        Objects.equals(this.observerId, getCorporationCorporationIdMiningObservers200Ok.observerId) &&
        Objects.equals(this.observerType, getCorporationCorporationIdMiningObservers200Ok.observerType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastUpdated, observerId, observerType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationCorporationIdMiningObservers200Ok {\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("    observerId: ").append(toIndentedString(observerId)).append("\n");
    sb.append("    observerType: ").append(toIndentedString(observerType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

