/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_ACCEPTOR_ID,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_ASSIGNEE_ID,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_AVAILABILITY,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_BUYOUT,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_COLLATERAL,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_CONTRACT_ID,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_DATE_ACCEPTED,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_DATE_COMPLETED,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_DATE_EXPIRED,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_DATE_ISSUED,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_DAYS_TO_COMPLETE,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_END_LOCATION_ID,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_FOR_CORPORATION,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_ISSUER_CORPORATION_ID,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_ISSUER_ID,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_PRICE,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_REWARD,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_START_LOCATION_ID,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_STATUS,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_TITLE,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_TYPE,
  GetCorporationsCorporationIdContracts200Ok.JSON_PROPERTY_VOLUME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCorporationsCorporationIdContracts200Ok implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ACCEPTOR_ID = "acceptor_id";
  private Integer acceptorId;

  public static final String JSON_PROPERTY_ASSIGNEE_ID = "assignee_id";
  private Integer assigneeId;

  /**
   * To whom the contract is available
   */
  public enum AvailabilityEnum {
    PUBLIC("public"),
    
    PERSONAL("personal"),
    
    CORPORATION("corporation"),
    
    ALLIANCE("alliance");

    private String value;

    AvailabilityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AvailabilityEnum fromValue(String value) {
      for (AvailabilityEnum b : AvailabilityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_AVAILABILITY = "availability";
  private AvailabilityEnum availability;

  public static final String JSON_PROPERTY_BUYOUT = "buyout";
  private Double buyout;

  public static final String JSON_PROPERTY_COLLATERAL = "collateral";
  private Double collateral;

  public static final String JSON_PROPERTY_CONTRACT_ID = "contract_id";
  private Integer contractId;

  public static final String JSON_PROPERTY_DATE_ACCEPTED = "date_accepted";
  private OffsetDateTime dateAccepted;

  public static final String JSON_PROPERTY_DATE_COMPLETED = "date_completed";
  private OffsetDateTime dateCompleted;

  public static final String JSON_PROPERTY_DATE_EXPIRED = "date_expired";
  private OffsetDateTime dateExpired;

  public static final String JSON_PROPERTY_DATE_ISSUED = "date_issued";
  private OffsetDateTime dateIssued;

  public static final String JSON_PROPERTY_DAYS_TO_COMPLETE = "days_to_complete";
  private Integer daysToComplete;

  public static final String JSON_PROPERTY_END_LOCATION_ID = "end_location_id";
  private Long endLocationId;

  public static final String JSON_PROPERTY_FOR_CORPORATION = "for_corporation";
  private Boolean forCorporation;

  public static final String JSON_PROPERTY_ISSUER_CORPORATION_ID = "issuer_corporation_id";
  private Integer issuerCorporationId;

  public static final String JSON_PROPERTY_ISSUER_ID = "issuer_id";
  private Integer issuerId;

  public static final String JSON_PROPERTY_PRICE = "price";
  private Double price;

  public static final String JSON_PROPERTY_REWARD = "reward";
  private Double reward;

  public static final String JSON_PROPERTY_START_LOCATION_ID = "start_location_id";
  private Long startLocationId;

  /**
   * Status of the the contract
   */
  public enum StatusEnum {
    OUTSTANDING("outstanding"),
    
    IN_PROGRESS("in_progress"),
    
    FINISHED_ISSUER("finished_issuer"),
    
    FINISHED_CONTRACTOR("finished_contractor"),
    
    FINISHED("finished"),
    
    CANCELLED("cancelled"),
    
    REJECTED("rejected"),
    
    FAILED("failed"),
    
    DELETED("deleted"),
    
    REVERSED("reversed");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  /**
   * Type of the contract
   */
  public enum TypeEnum {
    UNKNOWN("unknown"),
    
    ITEM_EXCHANGE("item_exchange"),
    
    AUCTION("auction"),
    
    COURIER("courier"),
    
    LOAN("loan");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_VOLUME = "volume";
  private Double volume;


  public GetCorporationsCorporationIdContracts200Ok acceptorId(Integer acceptorId) {
    
    this.acceptorId = acceptorId;
    return this;
  }

   /**
   * Who will accept the contract
   * @return acceptorId
  **/
  @ApiModelProperty(required = true, value = "Who will accept the contract")
  @JsonProperty(JSON_PROPERTY_ACCEPTOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAcceptorId() {
    return acceptorId;
  }


  public void setAcceptorId(Integer acceptorId) {
    this.acceptorId = acceptorId;
  }


  public GetCorporationsCorporationIdContracts200Ok assigneeId(Integer assigneeId) {
    
    this.assigneeId = assigneeId;
    return this;
  }

   /**
   * ID to whom the contract is assigned, can be corporation or character ID
   * @return assigneeId
  **/
  @ApiModelProperty(required = true, value = "ID to whom the contract is assigned, can be corporation or character ID")
  @JsonProperty(JSON_PROPERTY_ASSIGNEE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAssigneeId() {
    return assigneeId;
  }


  public void setAssigneeId(Integer assigneeId) {
    this.assigneeId = assigneeId;
  }


  public GetCorporationsCorporationIdContracts200Ok availability(AvailabilityEnum availability) {
    
    this.availability = availability;
    return this;
  }

   /**
   * To whom the contract is available
   * @return availability
  **/
  @ApiModelProperty(required = true, value = "To whom the contract is available")
  @JsonProperty(JSON_PROPERTY_AVAILABILITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public AvailabilityEnum getAvailability() {
    return availability;
  }


  public void setAvailability(AvailabilityEnum availability) {
    this.availability = availability;
  }


  public GetCorporationsCorporationIdContracts200Ok buyout(Double buyout) {
    
    this.buyout = buyout;
    return this;
  }

   /**
   * Buyout price (for Auctions only)
   * @return buyout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Buyout price (for Auctions only)")
  @JsonProperty(JSON_PROPERTY_BUYOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getBuyout() {
    return buyout;
  }


  public void setBuyout(Double buyout) {
    this.buyout = buyout;
  }


  public GetCorporationsCorporationIdContracts200Ok collateral(Double collateral) {
    
    this.collateral = collateral;
    return this;
  }

   /**
   * Collateral price (for Couriers only)
   * @return collateral
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Collateral price (for Couriers only)")
  @JsonProperty(JSON_PROPERTY_COLLATERAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCollateral() {
    return collateral;
  }


  public void setCollateral(Double collateral) {
    this.collateral = collateral;
  }


  public GetCorporationsCorporationIdContracts200Ok contractId(Integer contractId) {
    
    this.contractId = contractId;
    return this;
  }

   /**
   * contract_id integer
   * @return contractId
  **/
  @ApiModelProperty(required = true, value = "contract_id integer")
  @JsonProperty(JSON_PROPERTY_CONTRACT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getContractId() {
    return contractId;
  }


  public void setContractId(Integer contractId) {
    this.contractId = contractId;
  }


  public GetCorporationsCorporationIdContracts200Ok dateAccepted(OffsetDateTime dateAccepted) {
    
    this.dateAccepted = dateAccepted;
    return this;
  }

   /**
   * Date of confirmation of contract
   * @return dateAccepted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date of confirmation of contract")
  @JsonProperty(JSON_PROPERTY_DATE_ACCEPTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDateAccepted() {
    return dateAccepted;
  }


  public void setDateAccepted(OffsetDateTime dateAccepted) {
    this.dateAccepted = dateAccepted;
  }


  public GetCorporationsCorporationIdContracts200Ok dateCompleted(OffsetDateTime dateCompleted) {
    
    this.dateCompleted = dateCompleted;
    return this;
  }

   /**
   * Date of completed of contract
   * @return dateCompleted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date of completed of contract")
  @JsonProperty(JSON_PROPERTY_DATE_COMPLETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDateCompleted() {
    return dateCompleted;
  }


  public void setDateCompleted(OffsetDateTime dateCompleted) {
    this.dateCompleted = dateCompleted;
  }


  public GetCorporationsCorporationIdContracts200Ok dateExpired(OffsetDateTime dateExpired) {
    
    this.dateExpired = dateExpired;
    return this;
  }

   /**
   * Expiration date of the contract
   * @return dateExpired
  **/
  @ApiModelProperty(required = true, value = "Expiration date of the contract")
  @JsonProperty(JSON_PROPERTY_DATE_EXPIRED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getDateExpired() {
    return dateExpired;
  }


  public void setDateExpired(OffsetDateTime dateExpired) {
    this.dateExpired = dateExpired;
  }


  public GetCorporationsCorporationIdContracts200Ok dateIssued(OffsetDateTime dateIssued) {
    
    this.dateIssued = dateIssued;
    return this;
  }

   /**
   * Сreation date of the contract
   * @return dateIssued
  **/
  @ApiModelProperty(required = true, value = "Сreation date of the contract")
  @JsonProperty(JSON_PROPERTY_DATE_ISSUED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getDateIssued() {
    return dateIssued;
  }


  public void setDateIssued(OffsetDateTime dateIssued) {
    this.dateIssued = dateIssued;
  }


  public GetCorporationsCorporationIdContracts200Ok daysToComplete(Integer daysToComplete) {
    
    this.daysToComplete = daysToComplete;
    return this;
  }

   /**
   * Number of days to perform the contract
   * @return daysToComplete
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of days to perform the contract")
  @JsonProperty(JSON_PROPERTY_DAYS_TO_COMPLETE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDaysToComplete() {
    return daysToComplete;
  }


  public void setDaysToComplete(Integer daysToComplete) {
    this.daysToComplete = daysToComplete;
  }


  public GetCorporationsCorporationIdContracts200Ok endLocationId(Long endLocationId) {
    
    this.endLocationId = endLocationId;
    return this;
  }

   /**
   * End location ID (for Couriers contract)
   * @return endLocationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "End location ID (for Couriers contract)")
  @JsonProperty(JSON_PROPERTY_END_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getEndLocationId() {
    return endLocationId;
  }


  public void setEndLocationId(Long endLocationId) {
    this.endLocationId = endLocationId;
  }


  public GetCorporationsCorporationIdContracts200Ok forCorporation(Boolean forCorporation) {
    
    this.forCorporation = forCorporation;
    return this;
  }

   /**
   * true if the contract was issued on behalf of the issuer&#39;s corporation
   * @return forCorporation
  **/
  @ApiModelProperty(required = true, value = "true if the contract was issued on behalf of the issuer's corporation")
  @JsonProperty(JSON_PROPERTY_FOR_CORPORATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getForCorporation() {
    return forCorporation;
  }


  public void setForCorporation(Boolean forCorporation) {
    this.forCorporation = forCorporation;
  }


  public GetCorporationsCorporationIdContracts200Ok issuerCorporationId(Integer issuerCorporationId) {
    
    this.issuerCorporationId = issuerCorporationId;
    return this;
  }

   /**
   * Character&#39;s corporation ID for the issuer
   * @return issuerCorporationId
  **/
  @ApiModelProperty(required = true, value = "Character's corporation ID for the issuer")
  @JsonProperty(JSON_PROPERTY_ISSUER_CORPORATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIssuerCorporationId() {
    return issuerCorporationId;
  }


  public void setIssuerCorporationId(Integer issuerCorporationId) {
    this.issuerCorporationId = issuerCorporationId;
  }


  public GetCorporationsCorporationIdContracts200Ok issuerId(Integer issuerId) {
    
    this.issuerId = issuerId;
    return this;
  }

   /**
   * Character ID for the issuer
   * @return issuerId
  **/
  @ApiModelProperty(required = true, value = "Character ID for the issuer")
  @JsonProperty(JSON_PROPERTY_ISSUER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getIssuerId() {
    return issuerId;
  }


  public void setIssuerId(Integer issuerId) {
    this.issuerId = issuerId;
  }


  public GetCorporationsCorporationIdContracts200Ok price(Double price) {
    
    this.price = price;
    return this;
  }

   /**
   * Price of contract (for ItemsExchange and Auctions)
   * @return price
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Price of contract (for ItemsExchange and Auctions)")
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrice() {
    return price;
  }


  public void setPrice(Double price) {
    this.price = price;
  }


  public GetCorporationsCorporationIdContracts200Ok reward(Double reward) {
    
    this.reward = reward;
    return this;
  }

   /**
   * Remuneration for contract (for Couriers only)
   * @return reward
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Remuneration for contract (for Couriers only)")
  @JsonProperty(JSON_PROPERTY_REWARD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getReward() {
    return reward;
  }


  public void setReward(Double reward) {
    this.reward = reward;
  }


  public GetCorporationsCorporationIdContracts200Ok startLocationId(Long startLocationId) {
    
    this.startLocationId = startLocationId;
    return this;
  }

   /**
   * Start location ID (for Couriers contract)
   * @return startLocationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Start location ID (for Couriers contract)")
  @JsonProperty(JSON_PROPERTY_START_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getStartLocationId() {
    return startLocationId;
  }


  public void setStartLocationId(Long startLocationId) {
    this.startLocationId = startLocationId;
  }


  public GetCorporationsCorporationIdContracts200Ok status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Status of the the contract
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status of the the contract")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public GetCorporationsCorporationIdContracts200Ok title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Title of the contract
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Title of the contract")
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public GetCorporationsCorporationIdContracts200Ok type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of the contract
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type of the contract")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public GetCorporationsCorporationIdContracts200Ok volume(Double volume) {
    
    this.volume = volume;
    return this;
  }

   /**
   * Volume of items in the contract
   * @return volume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Volume of items in the contract")
  @JsonProperty(JSON_PROPERTY_VOLUME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVolume() {
    return volume;
  }


  public void setVolume(Double volume) {
    this.volume = volume;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationsCorporationIdContracts200Ok getCorporationsCorporationIdContracts200Ok = (GetCorporationsCorporationIdContracts200Ok) o;
    return Objects.equals(this.acceptorId, getCorporationsCorporationIdContracts200Ok.acceptorId) &&
        Objects.equals(this.assigneeId, getCorporationsCorporationIdContracts200Ok.assigneeId) &&
        Objects.equals(this.availability, getCorporationsCorporationIdContracts200Ok.availability) &&
        Objects.equals(this.buyout, getCorporationsCorporationIdContracts200Ok.buyout) &&
        Objects.equals(this.collateral, getCorporationsCorporationIdContracts200Ok.collateral) &&
        Objects.equals(this.contractId, getCorporationsCorporationIdContracts200Ok.contractId) &&
        Objects.equals(this.dateAccepted, getCorporationsCorporationIdContracts200Ok.dateAccepted) &&
        Objects.equals(this.dateCompleted, getCorporationsCorporationIdContracts200Ok.dateCompleted) &&
        Objects.equals(this.dateExpired, getCorporationsCorporationIdContracts200Ok.dateExpired) &&
        Objects.equals(this.dateIssued, getCorporationsCorporationIdContracts200Ok.dateIssued) &&
        Objects.equals(this.daysToComplete, getCorporationsCorporationIdContracts200Ok.daysToComplete) &&
        Objects.equals(this.endLocationId, getCorporationsCorporationIdContracts200Ok.endLocationId) &&
        Objects.equals(this.forCorporation, getCorporationsCorporationIdContracts200Ok.forCorporation) &&
        Objects.equals(this.issuerCorporationId, getCorporationsCorporationIdContracts200Ok.issuerCorporationId) &&
        Objects.equals(this.issuerId, getCorporationsCorporationIdContracts200Ok.issuerId) &&
        Objects.equals(this.price, getCorporationsCorporationIdContracts200Ok.price) &&
        Objects.equals(this.reward, getCorporationsCorporationIdContracts200Ok.reward) &&
        Objects.equals(this.startLocationId, getCorporationsCorporationIdContracts200Ok.startLocationId) &&
        Objects.equals(this.status, getCorporationsCorporationIdContracts200Ok.status) &&
        Objects.equals(this.title, getCorporationsCorporationIdContracts200Ok.title) &&
        Objects.equals(this.type, getCorporationsCorporationIdContracts200Ok.type) &&
        Objects.equals(this.volume, getCorporationsCorporationIdContracts200Ok.volume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceptorId, assigneeId, availability, buyout, collateral, contractId, dateAccepted, dateCompleted, dateExpired, dateIssued, daysToComplete, endLocationId, forCorporation, issuerCorporationId, issuerId, price, reward, startLocationId, status, title, type, volume);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationsCorporationIdContracts200Ok {\n");
    sb.append("    acceptorId: ").append(toIndentedString(acceptorId)).append("\n");
    sb.append("    assigneeId: ").append(toIndentedString(assigneeId)).append("\n");
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("    buyout: ").append(toIndentedString(buyout)).append("\n");
    sb.append("    collateral: ").append(toIndentedString(collateral)).append("\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    dateAccepted: ").append(toIndentedString(dateAccepted)).append("\n");
    sb.append("    dateCompleted: ").append(toIndentedString(dateCompleted)).append("\n");
    sb.append("    dateExpired: ").append(toIndentedString(dateExpired)).append("\n");
    sb.append("    dateIssued: ").append(toIndentedString(dateIssued)).append("\n");
    sb.append("    daysToComplete: ").append(toIndentedString(daysToComplete)).append("\n");
    sb.append("    endLocationId: ").append(toIndentedString(endLocationId)).append("\n");
    sb.append("    forCorporation: ").append(toIndentedString(forCorporation)).append("\n");
    sb.append("    issuerCorporationId: ").append(toIndentedString(issuerCorporationId)).append("\n");
    sb.append("    issuerId: ").append(toIndentedString(issuerId)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    reward: ").append(toIndentedString(reward)).append("\n");
    sb.append("    startLocationId: ").append(toIndentedString(startLocationId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

