/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetCorporationsCorporationIdWallets200Ok.JSON_PROPERTY_BALANCE,
  GetCorporationsCorporationIdWallets200Ok.JSON_PROPERTY_DIVISION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCorporationsCorporationIdWallets200Ok implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_BALANCE = "balance";
  private Double balance;

  public static final String JSON_PROPERTY_DIVISION = "division";
  private Integer division;


  public GetCorporationsCorporationIdWallets200Ok balance(Double balance) {
    
    this.balance = balance;
    return this;
  }

   /**
   * balance number
   * @return balance
  **/
  @ApiModelProperty(required = true, value = "balance number")
  @JsonProperty(JSON_PROPERTY_BALANCE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getBalance() {
    return balance;
  }


  public void setBalance(Double balance) {
    this.balance = balance;
  }


  public GetCorporationsCorporationIdWallets200Ok division(Integer division) {
    
    this.division = division;
    return this;
  }

   /**
   * division integer
   * minimum: 1
   * maximum: 7
   * @return division
  **/
  @ApiModelProperty(required = true, value = "division integer")
  @JsonProperty(JSON_PROPERTY_DIVISION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDivision() {
    return division;
  }


  public void setDivision(Integer division) {
    this.division = division;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationsCorporationIdWallets200Ok getCorporationsCorporationIdWallets200Ok = (GetCorporationsCorporationIdWallets200Ok) o;
    return Objects.equals(this.balance, getCorporationsCorporationIdWallets200Ok.balance) &&
        Objects.equals(this.division, getCorporationsCorporationIdWallets200Ok.division);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balance, division);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationsCorporationIdWallets200Ok {\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    division: ").append(toIndentedString(division)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

