/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_ACTIVITY_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_BLUEPRINT_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_BLUEPRINT_LOCATION_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_BLUEPRINT_TYPE_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_COMPLETED_CHARACTER_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_COMPLETED_DATE,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_COST,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_DURATION,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_END_DATE,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_FACILITY_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_INSTALLER_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_JOB_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_LICENSED_RUNS,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_LOCATION_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_OUTPUT_LOCATION_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_PAUSE_DATE,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_PROBABILITY,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_PRODUCT_TYPE_ID,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_RUNS,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_START_DATE,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_STATUS,
  GetCorporationsCorporationIdIndustryJobs200Ok.JSON_PROPERTY_SUCCESSFUL_RUNS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCorporationsCorporationIdIndustryJobs200Ok implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ACTIVITY_ID = "activity_id";
  private Integer activityId;

  public static final String JSON_PROPERTY_BLUEPRINT_ID = "blueprint_id";
  private Long blueprintId;

  public static final String JSON_PROPERTY_BLUEPRINT_LOCATION_ID = "blueprint_location_id";
  private Long blueprintLocationId;

  public static final String JSON_PROPERTY_BLUEPRINT_TYPE_ID = "blueprint_type_id";
  private Integer blueprintTypeId;

  public static final String JSON_PROPERTY_COMPLETED_CHARACTER_ID = "completed_character_id";
  private Integer completedCharacterId;

  public static final String JSON_PROPERTY_COMPLETED_DATE = "completed_date";
  private OffsetDateTime completedDate;

  public static final String JSON_PROPERTY_COST = "cost";
  private Double cost;

  public static final String JSON_PROPERTY_DURATION = "duration";
  private Integer duration;

  public static final String JSON_PROPERTY_END_DATE = "end_date";
  private OffsetDateTime endDate;

  public static final String JSON_PROPERTY_FACILITY_ID = "facility_id";
  private Long facilityId;

  public static final String JSON_PROPERTY_INSTALLER_ID = "installer_id";
  private Integer installerId;

  public static final String JSON_PROPERTY_JOB_ID = "job_id";
  private Integer jobId;

  public static final String JSON_PROPERTY_LICENSED_RUNS = "licensed_runs";
  private Integer licensedRuns;

  public static final String JSON_PROPERTY_LOCATION_ID = "location_id";
  private Long locationId;

  public static final String JSON_PROPERTY_OUTPUT_LOCATION_ID = "output_location_id";
  private Long outputLocationId;

  public static final String JSON_PROPERTY_PAUSE_DATE = "pause_date";
  private OffsetDateTime pauseDate;

  public static final String JSON_PROPERTY_PROBABILITY = "probability";
  private Float probability;

  public static final String JSON_PROPERTY_PRODUCT_TYPE_ID = "product_type_id";
  private Integer productTypeId;

  public static final String JSON_PROPERTY_RUNS = "runs";
  private Integer runs;

  public static final String JSON_PROPERTY_START_DATE = "start_date";
  private OffsetDateTime startDate;

  /**
   * status string
   */
  public enum StatusEnum {
    ACTIVE("active"),
    
    CANCELLED("cancelled"),
    
    DELIVERED("delivered"),
    
    PAUSED("paused"),
    
    READY("ready"),
    
    REVERTED("reverted");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_SUCCESSFUL_RUNS = "successful_runs";
  private Integer successfulRuns;


  public GetCorporationsCorporationIdIndustryJobs200Ok activityId(Integer activityId) {
    
    this.activityId = activityId;
    return this;
  }

   /**
   * Job activity ID
   * @return activityId
  **/
  @ApiModelProperty(required = true, value = "Job activity ID")
  @JsonProperty(JSON_PROPERTY_ACTIVITY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getActivityId() {
    return activityId;
  }


  public void setActivityId(Integer activityId) {
    this.activityId = activityId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok blueprintId(Long blueprintId) {
    
    this.blueprintId = blueprintId;
    return this;
  }

   /**
   * blueprint_id integer
   * @return blueprintId
  **/
  @ApiModelProperty(required = true, value = "blueprint_id integer")
  @JsonProperty(JSON_PROPERTY_BLUEPRINT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getBlueprintId() {
    return blueprintId;
  }


  public void setBlueprintId(Long blueprintId) {
    this.blueprintId = blueprintId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok blueprintLocationId(Long blueprintLocationId) {
    
    this.blueprintLocationId = blueprintLocationId;
    return this;
  }

   /**
   * Location ID of the location from which the blueprint was installed. Normally a station ID, but can also be an asset (e.g. container) or corporation facility
   * @return blueprintLocationId
  **/
  @ApiModelProperty(required = true, value = "Location ID of the location from which the blueprint was installed. Normally a station ID, but can also be an asset (e.g. container) or corporation facility")
  @JsonProperty(JSON_PROPERTY_BLUEPRINT_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getBlueprintLocationId() {
    return blueprintLocationId;
  }


  public void setBlueprintLocationId(Long blueprintLocationId) {
    this.blueprintLocationId = blueprintLocationId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok blueprintTypeId(Integer blueprintTypeId) {
    
    this.blueprintTypeId = blueprintTypeId;
    return this;
  }

   /**
   * blueprint_type_id integer
   * @return blueprintTypeId
  **/
  @ApiModelProperty(required = true, value = "blueprint_type_id integer")
  @JsonProperty(JSON_PROPERTY_BLUEPRINT_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getBlueprintTypeId() {
    return blueprintTypeId;
  }


  public void setBlueprintTypeId(Integer blueprintTypeId) {
    this.blueprintTypeId = blueprintTypeId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok completedCharacterId(Integer completedCharacterId) {
    
    this.completedCharacterId = completedCharacterId;
    return this;
  }

   /**
   * ID of the character which completed this job
   * @return completedCharacterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ID of the character which completed this job")
  @JsonProperty(JSON_PROPERTY_COMPLETED_CHARACTER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCompletedCharacterId() {
    return completedCharacterId;
  }


  public void setCompletedCharacterId(Integer completedCharacterId) {
    this.completedCharacterId = completedCharacterId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok completedDate(OffsetDateTime completedDate) {
    
    this.completedDate = completedDate;
    return this;
  }

   /**
   * Date and time when this job was completed
   * @return completedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date and time when this job was completed")
  @JsonProperty(JSON_PROPERTY_COMPLETED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCompletedDate() {
    return completedDate;
  }


  public void setCompletedDate(OffsetDateTime completedDate) {
    this.completedDate = completedDate;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok cost(Double cost) {
    
    this.cost = cost;
    return this;
  }

   /**
   * The sume of job installation fee and industry facility tax
   * @return cost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The sume of job installation fee and industry facility tax")
  @JsonProperty(JSON_PROPERTY_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCost() {
    return cost;
  }


  public void setCost(Double cost) {
    this.cost = cost;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok duration(Integer duration) {
    
    this.duration = duration;
    return this;
  }

   /**
   * Job duration in seconds
   * @return duration
  **/
  @ApiModelProperty(required = true, value = "Job duration in seconds")
  @JsonProperty(JSON_PROPERTY_DURATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDuration() {
    return duration;
  }


  public void setDuration(Integer duration) {
    this.duration = duration;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok endDate(OffsetDateTime endDate) {
    
    this.endDate = endDate;
    return this;
  }

   /**
   * Date and time when this job finished
   * @return endDate
  **/
  @ApiModelProperty(required = true, value = "Date and time when this job finished")
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getEndDate() {
    return endDate;
  }


  public void setEndDate(OffsetDateTime endDate) {
    this.endDate = endDate;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok facilityId(Long facilityId) {
    
    this.facilityId = facilityId;
    return this;
  }

   /**
   * ID of the facility where this job is running
   * @return facilityId
  **/
  @ApiModelProperty(required = true, value = "ID of the facility where this job is running")
  @JsonProperty(JSON_PROPERTY_FACILITY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getFacilityId() {
    return facilityId;
  }


  public void setFacilityId(Long facilityId) {
    this.facilityId = facilityId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok installerId(Integer installerId) {
    
    this.installerId = installerId;
    return this;
  }

   /**
   * ID of the character which installed this job
   * @return installerId
  **/
  @ApiModelProperty(required = true, value = "ID of the character which installed this job")
  @JsonProperty(JSON_PROPERTY_INSTALLER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getInstallerId() {
    return installerId;
  }


  public void setInstallerId(Integer installerId) {
    this.installerId = installerId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok jobId(Integer jobId) {
    
    this.jobId = jobId;
    return this;
  }

   /**
   * Unique job ID
   * @return jobId
  **/
  @ApiModelProperty(required = true, value = "Unique job ID")
  @JsonProperty(JSON_PROPERTY_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getJobId() {
    return jobId;
  }


  public void setJobId(Integer jobId) {
    this.jobId = jobId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok licensedRuns(Integer licensedRuns) {
    
    this.licensedRuns = licensedRuns;
    return this;
  }

   /**
   * Number of runs blueprint is licensed for
   * @return licensedRuns
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of runs blueprint is licensed for")
  @JsonProperty(JSON_PROPERTY_LICENSED_RUNS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLicensedRuns() {
    return licensedRuns;
  }


  public void setLicensedRuns(Integer licensedRuns) {
    this.licensedRuns = licensedRuns;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok locationId(Long locationId) {
    
    this.locationId = locationId;
    return this;
  }

   /**
   * ID of the location for the industry facility
   * @return locationId
  **/
  @ApiModelProperty(required = true, value = "ID of the location for the industry facility")
  @JsonProperty(JSON_PROPERTY_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getLocationId() {
    return locationId;
  }


  public void setLocationId(Long locationId) {
    this.locationId = locationId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok outputLocationId(Long outputLocationId) {
    
    this.outputLocationId = outputLocationId;
    return this;
  }

   /**
   * Location ID of the location to which the output of the job will be delivered. Normally a station ID, but can also be a corporation facility
   * @return outputLocationId
  **/
  @ApiModelProperty(required = true, value = "Location ID of the location to which the output of the job will be delivered. Normally a station ID, but can also be a corporation facility")
  @JsonProperty(JSON_PROPERTY_OUTPUT_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getOutputLocationId() {
    return outputLocationId;
  }


  public void setOutputLocationId(Long outputLocationId) {
    this.outputLocationId = outputLocationId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok pauseDate(OffsetDateTime pauseDate) {
    
    this.pauseDate = pauseDate;
    return this;
  }

   /**
   * Date and time when this job was paused (i.e. time when the facility where this job was installed went offline)
   * @return pauseDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date and time when this job was paused (i.e. time when the facility where this job was installed went offline)")
  @JsonProperty(JSON_PROPERTY_PAUSE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPauseDate() {
    return pauseDate;
  }


  public void setPauseDate(OffsetDateTime pauseDate) {
    this.pauseDate = pauseDate;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok probability(Float probability) {
    
    this.probability = probability;
    return this;
  }

   /**
   * Chance of success for invention
   * @return probability
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Chance of success for invention")
  @JsonProperty(JSON_PROPERTY_PROBABILITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getProbability() {
    return probability;
  }


  public void setProbability(Float probability) {
    this.probability = probability;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok productTypeId(Integer productTypeId) {
    
    this.productTypeId = productTypeId;
    return this;
  }

   /**
   * Type ID of product (manufactured, copied or invented)
   * @return productTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type ID of product (manufactured, copied or invented)")
  @JsonProperty(JSON_PROPERTY_PRODUCT_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProductTypeId() {
    return productTypeId;
  }


  public void setProductTypeId(Integer productTypeId) {
    this.productTypeId = productTypeId;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok runs(Integer runs) {
    
    this.runs = runs;
    return this;
  }

   /**
   * Number of runs for a manufacturing job, or number of copies to make for a blueprint copy
   * @return runs
  **/
  @ApiModelProperty(required = true, value = "Number of runs for a manufacturing job, or number of copies to make for a blueprint copy")
  @JsonProperty(JSON_PROPERTY_RUNS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRuns() {
    return runs;
  }


  public void setRuns(Integer runs) {
    this.runs = runs;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok startDate(OffsetDateTime startDate) {
    
    this.startDate = startDate;
    return this;
  }

   /**
   * Date and time when this job started
   * @return startDate
  **/
  @ApiModelProperty(required = true, value = "Date and time when this job started")
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getStartDate() {
    return startDate;
  }


  public void setStartDate(OffsetDateTime startDate) {
    this.startDate = startDate;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * status string
   * @return status
  **/
  @ApiModelProperty(required = true, value = "status string")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public GetCorporationsCorporationIdIndustryJobs200Ok successfulRuns(Integer successfulRuns) {
    
    this.successfulRuns = successfulRuns;
    return this;
  }

   /**
   * Number of successful runs for this job. Equal to runs unless this is an invention job
   * @return successfulRuns
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Number of successful runs for this job. Equal to runs unless this is an invention job")
  @JsonProperty(JSON_PROPERTY_SUCCESSFUL_RUNS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSuccessfulRuns() {
    return successfulRuns;
  }


  public void setSuccessfulRuns(Integer successfulRuns) {
    this.successfulRuns = successfulRuns;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationsCorporationIdIndustryJobs200Ok getCorporationsCorporationIdIndustryJobs200Ok = (GetCorporationsCorporationIdIndustryJobs200Ok) o;
    return Objects.equals(this.activityId, getCorporationsCorporationIdIndustryJobs200Ok.activityId) &&
        Objects.equals(this.blueprintId, getCorporationsCorporationIdIndustryJobs200Ok.blueprintId) &&
        Objects.equals(this.blueprintLocationId, getCorporationsCorporationIdIndustryJobs200Ok.blueprintLocationId) &&
        Objects.equals(this.blueprintTypeId, getCorporationsCorporationIdIndustryJobs200Ok.blueprintTypeId) &&
        Objects.equals(this.completedCharacterId, getCorporationsCorporationIdIndustryJobs200Ok.completedCharacterId) &&
        Objects.equals(this.completedDate, getCorporationsCorporationIdIndustryJobs200Ok.completedDate) &&
        Objects.equals(this.cost, getCorporationsCorporationIdIndustryJobs200Ok.cost) &&
        Objects.equals(this.duration, getCorporationsCorporationIdIndustryJobs200Ok.duration) &&
        Objects.equals(this.endDate, getCorporationsCorporationIdIndustryJobs200Ok.endDate) &&
        Objects.equals(this.facilityId, getCorporationsCorporationIdIndustryJobs200Ok.facilityId) &&
        Objects.equals(this.installerId, getCorporationsCorporationIdIndustryJobs200Ok.installerId) &&
        Objects.equals(this.jobId, getCorporationsCorporationIdIndustryJobs200Ok.jobId) &&
        Objects.equals(this.licensedRuns, getCorporationsCorporationIdIndustryJobs200Ok.licensedRuns) &&
        Objects.equals(this.locationId, getCorporationsCorporationIdIndustryJobs200Ok.locationId) &&
        Objects.equals(this.outputLocationId, getCorporationsCorporationIdIndustryJobs200Ok.outputLocationId) &&
        Objects.equals(this.pauseDate, getCorporationsCorporationIdIndustryJobs200Ok.pauseDate) &&
        Objects.equals(this.probability, getCorporationsCorporationIdIndustryJobs200Ok.probability) &&
        Objects.equals(this.productTypeId, getCorporationsCorporationIdIndustryJobs200Ok.productTypeId) &&
        Objects.equals(this.runs, getCorporationsCorporationIdIndustryJobs200Ok.runs) &&
        Objects.equals(this.startDate, getCorporationsCorporationIdIndustryJobs200Ok.startDate) &&
        Objects.equals(this.status, getCorporationsCorporationIdIndustryJobs200Ok.status) &&
        Objects.equals(this.successfulRuns, getCorporationsCorporationIdIndustryJobs200Ok.successfulRuns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activityId, blueprintId, blueprintLocationId, blueprintTypeId, completedCharacterId, completedDate, cost, duration, endDate, facilityId, installerId, jobId, licensedRuns, locationId, outputLocationId, pauseDate, probability, productTypeId, runs, startDate, status, successfulRuns);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationsCorporationIdIndustryJobs200Ok {\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    blueprintId: ").append(toIndentedString(blueprintId)).append("\n");
    sb.append("    blueprintLocationId: ").append(toIndentedString(blueprintLocationId)).append("\n");
    sb.append("    blueprintTypeId: ").append(toIndentedString(blueprintTypeId)).append("\n");
    sb.append("    completedCharacterId: ").append(toIndentedString(completedCharacterId)).append("\n");
    sb.append("    completedDate: ").append(toIndentedString(completedDate)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    facilityId: ").append(toIndentedString(facilityId)).append("\n");
    sb.append("    installerId: ").append(toIndentedString(installerId)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    licensedRuns: ").append(toIndentedString(licensedRuns)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    outputLocationId: ").append(toIndentedString(outputLocationId)).append("\n");
    sb.append("    pauseDate: ").append(toIndentedString(pauseDate)).append("\n");
    sb.append("    probability: ").append(toIndentedString(probability)).append("\n");
    sb.append("    productTypeId: ").append(toIndentedString(productTypeId)).append("\n");
    sb.append("    runs: ").append(toIndentedString(runs)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    successfulRuns: ").append(toIndentedString(successfulRuns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

