/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_ACTION,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_CHARACTER_ID,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_CONTAINER_ID,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_CONTAINER_TYPE_ID,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_LOCATION_FLAG,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_LOCATION_ID,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_LOGGED_AT,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_NEW_CONFIG_BITMASK,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_OLD_CONFIG_BITMASK,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_PASSWORD_TYPE,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_QUANTITY,
  GetCorporationsCorporationIdContainersLogs200Ok.JSON_PROPERTY_TYPE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCorporationsCorporationIdContainersLogs200Ok implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * action string
   */
  public enum ActionEnum {
    ADD("add"),
    
    ASSEMBLE("assemble"),
    
    CONFIGURE("configure"),
    
    ENTER_PASSWORD("enter_password"),
    
    LOCK("lock"),
    
    MOVE("move"),
    
    REPACKAGE("repackage"),
    
    SET_NAME("set_name"),
    
    SET_PASSWORD("set_password"),
    
    UNLOCK("unlock");

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACTION = "action";
  private ActionEnum action;

  public static final String JSON_PROPERTY_CHARACTER_ID = "character_id";
  private Integer characterId;

  public static final String JSON_PROPERTY_CONTAINER_ID = "container_id";
  private Long containerId;

  public static final String JSON_PROPERTY_CONTAINER_TYPE_ID = "container_type_id";
  private Integer containerTypeId;

  /**
   * location_flag string
   */
  public enum LocationFlagEnum {
    ASSETSAFETY("AssetSafety"),
    
    AUTOFIT("AutoFit"),
    
    BONUS("Bonus"),
    
    BOOSTER("Booster"),
    
    BOOSTERBAY("BoosterBay"),
    
    CAPSULE("Capsule"),
    
    CARGO("Cargo"),
    
    CORPDELIVERIES("CorpDeliveries"),
    
    CORPSAG1("CorpSAG1"),
    
    CORPSAG2("CorpSAG2"),
    
    CORPSAG3("CorpSAG3"),
    
    CORPSAG4("CorpSAG4"),
    
    CORPSAG5("CorpSAG5"),
    
    CORPSAG6("CorpSAG6"),
    
    CORPSAG7("CorpSAG7"),
    
    CRATELOOT("CrateLoot"),
    
    DELIVERIES("Deliveries"),
    
    DRONEBAY("DroneBay"),
    
    DUSTBATTLE("DustBattle"),
    
    DUSTDATABANK("DustDatabank"),
    
    FIGHTERBAY("FighterBay"),
    
    FIGHTERTUBE0("FighterTube0"),
    
    FIGHTERTUBE1("FighterTube1"),
    
    FIGHTERTUBE2("FighterTube2"),
    
    FIGHTERTUBE3("FighterTube3"),
    
    FIGHTERTUBE4("FighterTube4"),
    
    FLEETHANGAR("FleetHangar"),
    
    FRIGATEESCAPEBAY("FrigateEscapeBay"),
    
    HANGAR("Hangar"),
    
    HANGARALL("HangarAll"),
    
    HISLOT0("HiSlot0"),
    
    HISLOT1("HiSlot1"),
    
    HISLOT2("HiSlot2"),
    
    HISLOT3("HiSlot3"),
    
    HISLOT4("HiSlot4"),
    
    HISLOT5("HiSlot5"),
    
    HISLOT6("HiSlot6"),
    
    HISLOT7("HiSlot7"),
    
    HIDDENMODIFIERS("HiddenModifiers"),
    
    IMPLANT("Implant"),
    
    IMPOUNDED("Impounded"),
    
    JUNKYARDREPROCESSED("JunkyardReprocessed"),
    
    JUNKYARDTRASHED("JunkyardTrashed"),
    
    LOSLOT0("LoSlot0"),
    
    LOSLOT1("LoSlot1"),
    
    LOSLOT2("LoSlot2"),
    
    LOSLOT3("LoSlot3"),
    
    LOSLOT4("LoSlot4"),
    
    LOSLOT5("LoSlot5"),
    
    LOSLOT6("LoSlot6"),
    
    LOSLOT7("LoSlot7"),
    
    LOCKED("Locked"),
    
    MEDSLOT0("MedSlot0"),
    
    MEDSLOT1("MedSlot1"),
    
    MEDSLOT2("MedSlot2"),
    
    MEDSLOT3("MedSlot3"),
    
    MEDSLOT4("MedSlot4"),
    
    MEDSLOT5("MedSlot5"),
    
    MEDSLOT6("MedSlot6"),
    
    MEDSLOT7("MedSlot7"),
    
    OFFICEFOLDER("OfficeFolder"),
    
    PILOT("Pilot"),
    
    PLANETSURFACE("PlanetSurface"),
    
    QUAFEBAY("QuafeBay"),
    
    REWARD("Reward"),
    
    RIGSLOT0("RigSlot0"),
    
    RIGSLOT1("RigSlot1"),
    
    RIGSLOT2("RigSlot2"),
    
    RIGSLOT3("RigSlot3"),
    
    RIGSLOT4("RigSlot4"),
    
    RIGSLOT5("RigSlot5"),
    
    RIGSLOT6("RigSlot6"),
    
    RIGSLOT7("RigSlot7"),
    
    SECONDARYSTORAGE("SecondaryStorage"),
    
    SERVICESLOT0("ServiceSlot0"),
    
    SERVICESLOT1("ServiceSlot1"),
    
    SERVICESLOT2("ServiceSlot2"),
    
    SERVICESLOT3("ServiceSlot3"),
    
    SERVICESLOT4("ServiceSlot4"),
    
    SERVICESLOT5("ServiceSlot5"),
    
    SERVICESLOT6("ServiceSlot6"),
    
    SERVICESLOT7("ServiceSlot7"),
    
    SHIPHANGAR("ShipHangar"),
    
    SHIPOFFLINE("ShipOffline"),
    
    SKILL("Skill"),
    
    SKILLINTRAINING("SkillInTraining"),
    
    SPECIALIZEDAMMOHOLD("SpecializedAmmoHold"),
    
    SPECIALIZEDCOMMANDCENTERHOLD("SpecializedCommandCenterHold"),
    
    SPECIALIZEDFUELBAY("SpecializedFuelBay"),
    
    SPECIALIZEDGASHOLD("SpecializedGasHold"),
    
    SPECIALIZEDINDUSTRIALSHIPHOLD("SpecializedIndustrialShipHold"),
    
    SPECIALIZEDLARGESHIPHOLD("SpecializedLargeShipHold"),
    
    SPECIALIZEDMATERIALBAY("SpecializedMaterialBay"),
    
    SPECIALIZEDMEDIUMSHIPHOLD("SpecializedMediumShipHold"),
    
    SPECIALIZEDMINERALHOLD("SpecializedMineralHold"),
    
    SPECIALIZEDOREHOLD("SpecializedOreHold"),
    
    SPECIALIZEDPLANETARYCOMMODITIESHOLD("SpecializedPlanetaryCommoditiesHold"),
    
    SPECIALIZEDSALVAGEHOLD("SpecializedSalvageHold"),
    
    SPECIALIZEDSHIPHOLD("SpecializedShipHold"),
    
    SPECIALIZEDSMALLSHIPHOLD("SpecializedSmallShipHold"),
    
    STRUCTUREACTIVE("StructureActive"),
    
    STRUCTUREFUEL("StructureFuel"),
    
    STRUCTUREINACTIVE("StructureInactive"),
    
    STRUCTUREOFFLINE("StructureOffline"),
    
    SUBSYSTEMBAY("SubSystemBay"),
    
    SUBSYSTEMSLOT0("SubSystemSlot0"),
    
    SUBSYSTEMSLOT1("SubSystemSlot1"),
    
    SUBSYSTEMSLOT2("SubSystemSlot2"),
    
    SUBSYSTEMSLOT3("SubSystemSlot3"),
    
    SUBSYSTEMSLOT4("SubSystemSlot4"),
    
    SUBSYSTEMSLOT5("SubSystemSlot5"),
    
    SUBSYSTEMSLOT6("SubSystemSlot6"),
    
    SUBSYSTEMSLOT7("SubSystemSlot7"),
    
    UNLOCKED("Unlocked"),
    
    WALLET("Wallet"),
    
    WARDROBE("Wardrobe");

    private String value;

    LocationFlagEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static LocationFlagEnum fromValue(String value) {
      for (LocationFlagEnum b : LocationFlagEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_LOCATION_FLAG = "location_flag";
  private LocationFlagEnum locationFlag;

  public static final String JSON_PROPERTY_LOCATION_ID = "location_id";
  private Long locationId;

  public static final String JSON_PROPERTY_LOGGED_AT = "logged_at";
  private OffsetDateTime loggedAt;

  public static final String JSON_PROPERTY_NEW_CONFIG_BITMASK = "new_config_bitmask";
  private Integer newConfigBitmask;

  public static final String JSON_PROPERTY_OLD_CONFIG_BITMASK = "old_config_bitmask";
  private Integer oldConfigBitmask;

  /**
   * Type of password set if action is of type SetPassword or EnterPassword
   */
  public enum PasswordTypeEnum {
    CONFIG("config"),
    
    GENERAL("general");

    private String value;

    PasswordTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PasswordTypeEnum fromValue(String value) {
      for (PasswordTypeEnum b : PasswordTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PASSWORD_TYPE = "password_type";
  private PasswordTypeEnum passwordType;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Integer quantity;

  public static final String JSON_PROPERTY_TYPE_ID = "type_id";
  private Integer typeId;


  public GetCorporationsCorporationIdContainersLogs200Ok action(ActionEnum action) {
    
    this.action = action;
    return this;
  }

   /**
   * action string
   * @return action
  **/
  @ApiModelProperty(required = true, value = "action string")
  @JsonProperty(JSON_PROPERTY_ACTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ActionEnum getAction() {
    return action;
  }


  public void setAction(ActionEnum action) {
    this.action = action;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok characterId(Integer characterId) {
    
    this.characterId = characterId;
    return this;
  }

   /**
   * ID of the character who performed the action.
   * @return characterId
  **/
  @ApiModelProperty(required = true, value = "ID of the character who performed the action.")
  @JsonProperty(JSON_PROPERTY_CHARACTER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCharacterId() {
    return characterId;
  }


  public void setCharacterId(Integer characterId) {
    this.characterId = characterId;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok containerId(Long containerId) {
    
    this.containerId = containerId;
    return this;
  }

   /**
   * ID of the container
   * @return containerId
  **/
  @ApiModelProperty(required = true, value = "ID of the container")
  @JsonProperty(JSON_PROPERTY_CONTAINER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getContainerId() {
    return containerId;
  }


  public void setContainerId(Long containerId) {
    this.containerId = containerId;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok containerTypeId(Integer containerTypeId) {
    
    this.containerTypeId = containerTypeId;
    return this;
  }

   /**
   * Type ID of the container
   * @return containerTypeId
  **/
  @ApiModelProperty(required = true, value = "Type ID of the container")
  @JsonProperty(JSON_PROPERTY_CONTAINER_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getContainerTypeId() {
    return containerTypeId;
  }


  public void setContainerTypeId(Integer containerTypeId) {
    this.containerTypeId = containerTypeId;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok locationFlag(LocationFlagEnum locationFlag) {
    
    this.locationFlag = locationFlag;
    return this;
  }

   /**
   * location_flag string
   * @return locationFlag
  **/
  @ApiModelProperty(required = true, value = "location_flag string")
  @JsonProperty(JSON_PROPERTY_LOCATION_FLAG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocationFlagEnum getLocationFlag() {
    return locationFlag;
  }


  public void setLocationFlag(LocationFlagEnum locationFlag) {
    this.locationFlag = locationFlag;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok locationId(Long locationId) {
    
    this.locationId = locationId;
    return this;
  }

   /**
   * location_id integer
   * @return locationId
  **/
  @ApiModelProperty(required = true, value = "location_id integer")
  @JsonProperty(JSON_PROPERTY_LOCATION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getLocationId() {
    return locationId;
  }


  public void setLocationId(Long locationId) {
    this.locationId = locationId;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok loggedAt(OffsetDateTime loggedAt) {
    
    this.loggedAt = loggedAt;
    return this;
  }

   /**
   * Timestamp when this log was created
   * @return loggedAt
  **/
  @ApiModelProperty(required = true, value = "Timestamp when this log was created")
  @JsonProperty(JSON_PROPERTY_LOGGED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLoggedAt() {
    return loggedAt;
  }


  public void setLoggedAt(OffsetDateTime loggedAt) {
    this.loggedAt = loggedAt;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok newConfigBitmask(Integer newConfigBitmask) {
    
    this.newConfigBitmask = newConfigBitmask;
    return this;
  }

   /**
   * new_config_bitmask integer
   * @return newConfigBitmask
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "new_config_bitmask integer")
  @JsonProperty(JSON_PROPERTY_NEW_CONFIG_BITMASK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNewConfigBitmask() {
    return newConfigBitmask;
  }


  public void setNewConfigBitmask(Integer newConfigBitmask) {
    this.newConfigBitmask = newConfigBitmask;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok oldConfigBitmask(Integer oldConfigBitmask) {
    
    this.oldConfigBitmask = oldConfigBitmask;
    return this;
  }

   /**
   * old_config_bitmask integer
   * @return oldConfigBitmask
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "old_config_bitmask integer")
  @JsonProperty(JSON_PROPERTY_OLD_CONFIG_BITMASK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOldConfigBitmask() {
    return oldConfigBitmask;
  }


  public void setOldConfigBitmask(Integer oldConfigBitmask) {
    this.oldConfigBitmask = oldConfigBitmask;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok passwordType(PasswordTypeEnum passwordType) {
    
    this.passwordType = passwordType;
    return this;
  }

   /**
   * Type of password set if action is of type SetPassword or EnterPassword
   * @return passwordType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type of password set if action is of type SetPassword or EnterPassword")
  @JsonProperty(JSON_PROPERTY_PASSWORD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PasswordTypeEnum getPasswordType() {
    return passwordType;
  }


  public void setPasswordType(PasswordTypeEnum passwordType) {
    this.passwordType = passwordType;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * Quantity of the item being acted upon
   * @return quantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Quantity of the item being acted upon")
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQuantity() {
    return quantity;
  }


  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public GetCorporationsCorporationIdContainersLogs200Ok typeId(Integer typeId) {
    
    this.typeId = typeId;
    return this;
  }

   /**
   * Type ID of the item being acted upon
   * @return typeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type ID of the item being acted upon")
  @JsonProperty(JSON_PROPERTY_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTypeId() {
    return typeId;
  }


  public void setTypeId(Integer typeId) {
    this.typeId = typeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationsCorporationIdContainersLogs200Ok getCorporationsCorporationIdContainersLogs200Ok = (GetCorporationsCorporationIdContainersLogs200Ok) o;
    return Objects.equals(this.action, getCorporationsCorporationIdContainersLogs200Ok.action) &&
        Objects.equals(this.characterId, getCorporationsCorporationIdContainersLogs200Ok.characterId) &&
        Objects.equals(this.containerId, getCorporationsCorporationIdContainersLogs200Ok.containerId) &&
        Objects.equals(this.containerTypeId, getCorporationsCorporationIdContainersLogs200Ok.containerTypeId) &&
        Objects.equals(this.locationFlag, getCorporationsCorporationIdContainersLogs200Ok.locationFlag) &&
        Objects.equals(this.locationId, getCorporationsCorporationIdContainersLogs200Ok.locationId) &&
        Objects.equals(this.loggedAt, getCorporationsCorporationIdContainersLogs200Ok.loggedAt) &&
        Objects.equals(this.newConfigBitmask, getCorporationsCorporationIdContainersLogs200Ok.newConfigBitmask) &&
        Objects.equals(this.oldConfigBitmask, getCorporationsCorporationIdContainersLogs200Ok.oldConfigBitmask) &&
        Objects.equals(this.passwordType, getCorporationsCorporationIdContainersLogs200Ok.passwordType) &&
        Objects.equals(this.quantity, getCorporationsCorporationIdContainersLogs200Ok.quantity) &&
        Objects.equals(this.typeId, getCorporationsCorporationIdContainersLogs200Ok.typeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, characterId, containerId, containerTypeId, locationFlag, locationId, loggedAt, newConfigBitmask, oldConfigBitmask, passwordType, quantity, typeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationsCorporationIdContainersLogs200Ok {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    characterId: ").append(toIndentedString(characterId)).append("\n");
    sb.append("    containerId: ").append(toIndentedString(containerId)).append("\n");
    sb.append("    containerTypeId: ").append(toIndentedString(containerTypeId)).append("\n");
    sb.append("    locationFlag: ").append(toIndentedString(locationFlag)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    loggedAt: ").append(toIndentedString(loggedAt)).append("\n");
    sb.append("    newConfigBitmask: ").append(toIndentedString(newConfigBitmask)).append("\n");
    sb.append("    oldConfigBitmask: ").append(toIndentedString(oldConfigBitmask)).append("\n");
    sb.append("    passwordType: ").append(toIndentedString(passwordType)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

