/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetCharactersCharacterIdMailLabelsLabel;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetCharactersCharacterIdMailLabelsOk.JSON_PROPERTY_LABELS,
  GetCharactersCharacterIdMailLabelsOk.JSON_PROPERTY_TOTAL_UNREAD_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCharactersCharacterIdMailLabelsOk implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_LABELS = "labels";
  private List<GetCharactersCharacterIdMailLabelsLabel> labels = null;

  public static final String JSON_PROPERTY_TOTAL_UNREAD_COUNT = "total_unread_count";
  private Integer totalUnreadCount;


  public GetCharactersCharacterIdMailLabelsOk labels(List<GetCharactersCharacterIdMailLabelsLabel> labels) {
    
    this.labels = labels;
    return this;
  }

  public GetCharactersCharacterIdMailLabelsOk addLabelsItem(GetCharactersCharacterIdMailLabelsLabel labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * labels array
   * @return labels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "labels array")
  @JsonProperty(JSON_PROPERTY_LABELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GetCharactersCharacterIdMailLabelsLabel> getLabels() {
    return labels;
  }


  public void setLabels(List<GetCharactersCharacterIdMailLabelsLabel> labels) {
    this.labels = labels;
  }


  public GetCharactersCharacterIdMailLabelsOk totalUnreadCount(Integer totalUnreadCount) {
    
    this.totalUnreadCount = totalUnreadCount;
    return this;
  }

   /**
   * total_unread_count integer
   * minimum: 0
   * @return totalUnreadCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "total_unread_count integer")
  @JsonProperty(JSON_PROPERTY_TOTAL_UNREAD_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalUnreadCount() {
    return totalUnreadCount;
  }


  public void setTotalUnreadCount(Integer totalUnreadCount) {
    this.totalUnreadCount = totalUnreadCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdMailLabelsOk getCharactersCharacterIdMailLabelsOk = (GetCharactersCharacterIdMailLabelsOk) o;
    return Objects.equals(this.labels, getCharactersCharacterIdMailLabelsOk.labels) &&
        Objects.equals(this.totalUnreadCount, getCharactersCharacterIdMailLabelsOk.totalUnreadCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labels, totalUnreadCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdMailLabelsOk {\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    totalUnreadCount: ").append(toIndentedString(totalUnreadCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

