/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * industry object
 */
@ApiModel(description = "industry object")
@JsonPropertyOrder({
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_HACKING_SUCCESSES,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_CANCELLED,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_COPY_BLUEPRINT,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_INVENTION,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_ASTEROID,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_ASTEROID_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_CHARGE,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_CHARGE_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_COMMODITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_COMMODITY_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DEPLOYABLE,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DEPLOYABLE_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DRONE,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DRONE_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_IMPLANT,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_IMPLANT_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_MODULE,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_MODULE_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_OTHER,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_OTHER_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SHIP,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SHIP_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_STRUCTURE,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_STRUCTURE_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SUBSYSTEM,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SUBSYSTEM_QUANTITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_MATERIAL_PRODUCTIVITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_COMPLETED_TIME_PRODUCTIVITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_STARTED_COPY_BLUEPRINT,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_STARTED_INVENTION,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_STARTED_MANUFACTURE,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_STARTED_MATERIAL_PRODUCTIVITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_JOBS_STARTED_TIME_PRODUCTIVITY,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_REPROCESS_ITEM,
  GetCharactersCharacterIdStatsIndustry.JSON_PROPERTY_REPROCESS_ITEM_QUANTITY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCharactersCharacterIdStatsIndustry implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_HACKING_SUCCESSES = "hacking_successes";
  private Long hackingSuccesses;

  public static final String JSON_PROPERTY_JOBS_CANCELLED = "jobs_cancelled";
  private Long jobsCancelled;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_COPY_BLUEPRINT = "jobs_completed_copy_blueprint";
  private Long jobsCompletedCopyBlueprint;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_INVENTION = "jobs_completed_invention";
  private Long jobsCompletedInvention;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE = "jobs_completed_manufacture";
  private Long jobsCompletedManufacture;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_ASTEROID = "jobs_completed_manufacture_asteroid";
  private Long jobsCompletedManufactureAsteroid;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_ASTEROID_QUANTITY = "jobs_completed_manufacture_asteroid_quantity";
  private Long jobsCompletedManufactureAsteroidQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_CHARGE = "jobs_completed_manufacture_charge";
  private Long jobsCompletedManufactureCharge;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_CHARGE_QUANTITY = "jobs_completed_manufacture_charge_quantity";
  private Long jobsCompletedManufactureChargeQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_COMMODITY = "jobs_completed_manufacture_commodity";
  private Long jobsCompletedManufactureCommodity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_COMMODITY_QUANTITY = "jobs_completed_manufacture_commodity_quantity";
  private Long jobsCompletedManufactureCommodityQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DEPLOYABLE = "jobs_completed_manufacture_deployable";
  private Long jobsCompletedManufactureDeployable;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DEPLOYABLE_QUANTITY = "jobs_completed_manufacture_deployable_quantity";
  private Long jobsCompletedManufactureDeployableQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DRONE = "jobs_completed_manufacture_drone";
  private Long jobsCompletedManufactureDrone;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DRONE_QUANTITY = "jobs_completed_manufacture_drone_quantity";
  private Long jobsCompletedManufactureDroneQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_IMPLANT = "jobs_completed_manufacture_implant";
  private Long jobsCompletedManufactureImplant;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_IMPLANT_QUANTITY = "jobs_completed_manufacture_implant_quantity";
  private Long jobsCompletedManufactureImplantQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_MODULE = "jobs_completed_manufacture_module";
  private Long jobsCompletedManufactureModule;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_MODULE_QUANTITY = "jobs_completed_manufacture_module_quantity";
  private Long jobsCompletedManufactureModuleQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_OTHER = "jobs_completed_manufacture_other";
  private Long jobsCompletedManufactureOther;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_OTHER_QUANTITY = "jobs_completed_manufacture_other_quantity";
  private Long jobsCompletedManufactureOtherQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SHIP = "jobs_completed_manufacture_ship";
  private Long jobsCompletedManufactureShip;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SHIP_QUANTITY = "jobs_completed_manufacture_ship_quantity";
  private Long jobsCompletedManufactureShipQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_STRUCTURE = "jobs_completed_manufacture_structure";
  private Long jobsCompletedManufactureStructure;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_STRUCTURE_QUANTITY = "jobs_completed_manufacture_structure_quantity";
  private Long jobsCompletedManufactureStructureQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SUBSYSTEM = "jobs_completed_manufacture_subsystem";
  private Long jobsCompletedManufactureSubsystem;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SUBSYSTEM_QUANTITY = "jobs_completed_manufacture_subsystem_quantity";
  private Long jobsCompletedManufactureSubsystemQuantity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_MATERIAL_PRODUCTIVITY = "jobs_completed_material_productivity";
  private Long jobsCompletedMaterialProductivity;

  public static final String JSON_PROPERTY_JOBS_COMPLETED_TIME_PRODUCTIVITY = "jobs_completed_time_productivity";
  private Long jobsCompletedTimeProductivity;

  public static final String JSON_PROPERTY_JOBS_STARTED_COPY_BLUEPRINT = "jobs_started_copy_blueprint";
  private Long jobsStartedCopyBlueprint;

  public static final String JSON_PROPERTY_JOBS_STARTED_INVENTION = "jobs_started_invention";
  private Long jobsStartedInvention;

  public static final String JSON_PROPERTY_JOBS_STARTED_MANUFACTURE = "jobs_started_manufacture";
  private Long jobsStartedManufacture;

  public static final String JSON_PROPERTY_JOBS_STARTED_MATERIAL_PRODUCTIVITY = "jobs_started_material_productivity";
  private Long jobsStartedMaterialProductivity;

  public static final String JSON_PROPERTY_JOBS_STARTED_TIME_PRODUCTIVITY = "jobs_started_time_productivity";
  private Long jobsStartedTimeProductivity;

  public static final String JSON_PROPERTY_REPROCESS_ITEM = "reprocess_item";
  private Long reprocessItem;

  public static final String JSON_PROPERTY_REPROCESS_ITEM_QUANTITY = "reprocess_item_quantity";
  private Long reprocessItemQuantity;


  public GetCharactersCharacterIdStatsIndustry hackingSuccesses(Long hackingSuccesses) {
    
    this.hackingSuccesses = hackingSuccesses;
    return this;
  }

   /**
   * hacking_successes integer
   * @return hackingSuccesses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "hacking_successes integer")
  @JsonProperty(JSON_PROPERTY_HACKING_SUCCESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHackingSuccesses() {
    return hackingSuccesses;
  }


  public void setHackingSuccesses(Long hackingSuccesses) {
    this.hackingSuccesses = hackingSuccesses;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCancelled(Long jobsCancelled) {
    
    this.jobsCancelled = jobsCancelled;
    return this;
  }

   /**
   * jobs_cancelled integer
   * @return jobsCancelled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_cancelled integer")
  @JsonProperty(JSON_PROPERTY_JOBS_CANCELLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCancelled() {
    return jobsCancelled;
  }


  public void setJobsCancelled(Long jobsCancelled) {
    this.jobsCancelled = jobsCancelled;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedCopyBlueprint(Long jobsCompletedCopyBlueprint) {
    
    this.jobsCompletedCopyBlueprint = jobsCompletedCopyBlueprint;
    return this;
  }

   /**
   * jobs_completed_copy_blueprint integer
   * @return jobsCompletedCopyBlueprint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_copy_blueprint integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_COPY_BLUEPRINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedCopyBlueprint() {
    return jobsCompletedCopyBlueprint;
  }


  public void setJobsCompletedCopyBlueprint(Long jobsCompletedCopyBlueprint) {
    this.jobsCompletedCopyBlueprint = jobsCompletedCopyBlueprint;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedInvention(Long jobsCompletedInvention) {
    
    this.jobsCompletedInvention = jobsCompletedInvention;
    return this;
  }

   /**
   * jobs_completed_invention integer
   * @return jobsCompletedInvention
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_invention integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_INVENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedInvention() {
    return jobsCompletedInvention;
  }


  public void setJobsCompletedInvention(Long jobsCompletedInvention) {
    this.jobsCompletedInvention = jobsCompletedInvention;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufacture(Long jobsCompletedManufacture) {
    
    this.jobsCompletedManufacture = jobsCompletedManufacture;
    return this;
  }

   /**
   * jobs_completed_manufacture integer
   * @return jobsCompletedManufacture
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufacture() {
    return jobsCompletedManufacture;
  }


  public void setJobsCompletedManufacture(Long jobsCompletedManufacture) {
    this.jobsCompletedManufacture = jobsCompletedManufacture;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureAsteroid(Long jobsCompletedManufactureAsteroid) {
    
    this.jobsCompletedManufactureAsteroid = jobsCompletedManufactureAsteroid;
    return this;
  }

   /**
   * jobs_completed_manufacture_asteroid integer
   * @return jobsCompletedManufactureAsteroid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_asteroid integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_ASTEROID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureAsteroid() {
    return jobsCompletedManufactureAsteroid;
  }


  public void setJobsCompletedManufactureAsteroid(Long jobsCompletedManufactureAsteroid) {
    this.jobsCompletedManufactureAsteroid = jobsCompletedManufactureAsteroid;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureAsteroidQuantity(Long jobsCompletedManufactureAsteroidQuantity) {
    
    this.jobsCompletedManufactureAsteroidQuantity = jobsCompletedManufactureAsteroidQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_asteroid_quantity integer
   * @return jobsCompletedManufactureAsteroidQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_asteroid_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_ASTEROID_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureAsteroidQuantity() {
    return jobsCompletedManufactureAsteroidQuantity;
  }


  public void setJobsCompletedManufactureAsteroidQuantity(Long jobsCompletedManufactureAsteroidQuantity) {
    this.jobsCompletedManufactureAsteroidQuantity = jobsCompletedManufactureAsteroidQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureCharge(Long jobsCompletedManufactureCharge) {
    
    this.jobsCompletedManufactureCharge = jobsCompletedManufactureCharge;
    return this;
  }

   /**
   * jobs_completed_manufacture_charge integer
   * @return jobsCompletedManufactureCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_charge integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_CHARGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureCharge() {
    return jobsCompletedManufactureCharge;
  }


  public void setJobsCompletedManufactureCharge(Long jobsCompletedManufactureCharge) {
    this.jobsCompletedManufactureCharge = jobsCompletedManufactureCharge;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureChargeQuantity(Long jobsCompletedManufactureChargeQuantity) {
    
    this.jobsCompletedManufactureChargeQuantity = jobsCompletedManufactureChargeQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_charge_quantity integer
   * @return jobsCompletedManufactureChargeQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_charge_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_CHARGE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureChargeQuantity() {
    return jobsCompletedManufactureChargeQuantity;
  }


  public void setJobsCompletedManufactureChargeQuantity(Long jobsCompletedManufactureChargeQuantity) {
    this.jobsCompletedManufactureChargeQuantity = jobsCompletedManufactureChargeQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureCommodity(Long jobsCompletedManufactureCommodity) {
    
    this.jobsCompletedManufactureCommodity = jobsCompletedManufactureCommodity;
    return this;
  }

   /**
   * jobs_completed_manufacture_commodity integer
   * @return jobsCompletedManufactureCommodity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_commodity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_COMMODITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureCommodity() {
    return jobsCompletedManufactureCommodity;
  }


  public void setJobsCompletedManufactureCommodity(Long jobsCompletedManufactureCommodity) {
    this.jobsCompletedManufactureCommodity = jobsCompletedManufactureCommodity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureCommodityQuantity(Long jobsCompletedManufactureCommodityQuantity) {
    
    this.jobsCompletedManufactureCommodityQuantity = jobsCompletedManufactureCommodityQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_commodity_quantity integer
   * @return jobsCompletedManufactureCommodityQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_commodity_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_COMMODITY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureCommodityQuantity() {
    return jobsCompletedManufactureCommodityQuantity;
  }


  public void setJobsCompletedManufactureCommodityQuantity(Long jobsCompletedManufactureCommodityQuantity) {
    this.jobsCompletedManufactureCommodityQuantity = jobsCompletedManufactureCommodityQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureDeployable(Long jobsCompletedManufactureDeployable) {
    
    this.jobsCompletedManufactureDeployable = jobsCompletedManufactureDeployable;
    return this;
  }

   /**
   * jobs_completed_manufacture_deployable integer
   * @return jobsCompletedManufactureDeployable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_deployable integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DEPLOYABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureDeployable() {
    return jobsCompletedManufactureDeployable;
  }


  public void setJobsCompletedManufactureDeployable(Long jobsCompletedManufactureDeployable) {
    this.jobsCompletedManufactureDeployable = jobsCompletedManufactureDeployable;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureDeployableQuantity(Long jobsCompletedManufactureDeployableQuantity) {
    
    this.jobsCompletedManufactureDeployableQuantity = jobsCompletedManufactureDeployableQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_deployable_quantity integer
   * @return jobsCompletedManufactureDeployableQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_deployable_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DEPLOYABLE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureDeployableQuantity() {
    return jobsCompletedManufactureDeployableQuantity;
  }


  public void setJobsCompletedManufactureDeployableQuantity(Long jobsCompletedManufactureDeployableQuantity) {
    this.jobsCompletedManufactureDeployableQuantity = jobsCompletedManufactureDeployableQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureDrone(Long jobsCompletedManufactureDrone) {
    
    this.jobsCompletedManufactureDrone = jobsCompletedManufactureDrone;
    return this;
  }

   /**
   * jobs_completed_manufacture_drone integer
   * @return jobsCompletedManufactureDrone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_drone integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DRONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureDrone() {
    return jobsCompletedManufactureDrone;
  }


  public void setJobsCompletedManufactureDrone(Long jobsCompletedManufactureDrone) {
    this.jobsCompletedManufactureDrone = jobsCompletedManufactureDrone;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureDroneQuantity(Long jobsCompletedManufactureDroneQuantity) {
    
    this.jobsCompletedManufactureDroneQuantity = jobsCompletedManufactureDroneQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_drone_quantity integer
   * @return jobsCompletedManufactureDroneQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_drone_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_DRONE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureDroneQuantity() {
    return jobsCompletedManufactureDroneQuantity;
  }


  public void setJobsCompletedManufactureDroneQuantity(Long jobsCompletedManufactureDroneQuantity) {
    this.jobsCompletedManufactureDroneQuantity = jobsCompletedManufactureDroneQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureImplant(Long jobsCompletedManufactureImplant) {
    
    this.jobsCompletedManufactureImplant = jobsCompletedManufactureImplant;
    return this;
  }

   /**
   * jobs_completed_manufacture_implant integer
   * @return jobsCompletedManufactureImplant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_implant integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_IMPLANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureImplant() {
    return jobsCompletedManufactureImplant;
  }


  public void setJobsCompletedManufactureImplant(Long jobsCompletedManufactureImplant) {
    this.jobsCompletedManufactureImplant = jobsCompletedManufactureImplant;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureImplantQuantity(Long jobsCompletedManufactureImplantQuantity) {
    
    this.jobsCompletedManufactureImplantQuantity = jobsCompletedManufactureImplantQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_implant_quantity integer
   * @return jobsCompletedManufactureImplantQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_implant_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_IMPLANT_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureImplantQuantity() {
    return jobsCompletedManufactureImplantQuantity;
  }


  public void setJobsCompletedManufactureImplantQuantity(Long jobsCompletedManufactureImplantQuantity) {
    this.jobsCompletedManufactureImplantQuantity = jobsCompletedManufactureImplantQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureModule(Long jobsCompletedManufactureModule) {
    
    this.jobsCompletedManufactureModule = jobsCompletedManufactureModule;
    return this;
  }

   /**
   * jobs_completed_manufacture_module integer
   * @return jobsCompletedManufactureModule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_module integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_MODULE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureModule() {
    return jobsCompletedManufactureModule;
  }


  public void setJobsCompletedManufactureModule(Long jobsCompletedManufactureModule) {
    this.jobsCompletedManufactureModule = jobsCompletedManufactureModule;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureModuleQuantity(Long jobsCompletedManufactureModuleQuantity) {
    
    this.jobsCompletedManufactureModuleQuantity = jobsCompletedManufactureModuleQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_module_quantity integer
   * @return jobsCompletedManufactureModuleQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_module_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_MODULE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureModuleQuantity() {
    return jobsCompletedManufactureModuleQuantity;
  }


  public void setJobsCompletedManufactureModuleQuantity(Long jobsCompletedManufactureModuleQuantity) {
    this.jobsCompletedManufactureModuleQuantity = jobsCompletedManufactureModuleQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureOther(Long jobsCompletedManufactureOther) {
    
    this.jobsCompletedManufactureOther = jobsCompletedManufactureOther;
    return this;
  }

   /**
   * jobs_completed_manufacture_other integer
   * @return jobsCompletedManufactureOther
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_other integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_OTHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureOther() {
    return jobsCompletedManufactureOther;
  }


  public void setJobsCompletedManufactureOther(Long jobsCompletedManufactureOther) {
    this.jobsCompletedManufactureOther = jobsCompletedManufactureOther;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureOtherQuantity(Long jobsCompletedManufactureOtherQuantity) {
    
    this.jobsCompletedManufactureOtherQuantity = jobsCompletedManufactureOtherQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_other_quantity integer
   * @return jobsCompletedManufactureOtherQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_other_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_OTHER_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureOtherQuantity() {
    return jobsCompletedManufactureOtherQuantity;
  }


  public void setJobsCompletedManufactureOtherQuantity(Long jobsCompletedManufactureOtherQuantity) {
    this.jobsCompletedManufactureOtherQuantity = jobsCompletedManufactureOtherQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureShip(Long jobsCompletedManufactureShip) {
    
    this.jobsCompletedManufactureShip = jobsCompletedManufactureShip;
    return this;
  }

   /**
   * jobs_completed_manufacture_ship integer
   * @return jobsCompletedManufactureShip
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_ship integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SHIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureShip() {
    return jobsCompletedManufactureShip;
  }


  public void setJobsCompletedManufactureShip(Long jobsCompletedManufactureShip) {
    this.jobsCompletedManufactureShip = jobsCompletedManufactureShip;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureShipQuantity(Long jobsCompletedManufactureShipQuantity) {
    
    this.jobsCompletedManufactureShipQuantity = jobsCompletedManufactureShipQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_ship_quantity integer
   * @return jobsCompletedManufactureShipQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_ship_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SHIP_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureShipQuantity() {
    return jobsCompletedManufactureShipQuantity;
  }


  public void setJobsCompletedManufactureShipQuantity(Long jobsCompletedManufactureShipQuantity) {
    this.jobsCompletedManufactureShipQuantity = jobsCompletedManufactureShipQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureStructure(Long jobsCompletedManufactureStructure) {
    
    this.jobsCompletedManufactureStructure = jobsCompletedManufactureStructure;
    return this;
  }

   /**
   * jobs_completed_manufacture_structure integer
   * @return jobsCompletedManufactureStructure
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_structure integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_STRUCTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureStructure() {
    return jobsCompletedManufactureStructure;
  }


  public void setJobsCompletedManufactureStructure(Long jobsCompletedManufactureStructure) {
    this.jobsCompletedManufactureStructure = jobsCompletedManufactureStructure;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureStructureQuantity(Long jobsCompletedManufactureStructureQuantity) {
    
    this.jobsCompletedManufactureStructureQuantity = jobsCompletedManufactureStructureQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_structure_quantity integer
   * @return jobsCompletedManufactureStructureQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_structure_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_STRUCTURE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureStructureQuantity() {
    return jobsCompletedManufactureStructureQuantity;
  }


  public void setJobsCompletedManufactureStructureQuantity(Long jobsCompletedManufactureStructureQuantity) {
    this.jobsCompletedManufactureStructureQuantity = jobsCompletedManufactureStructureQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureSubsystem(Long jobsCompletedManufactureSubsystem) {
    
    this.jobsCompletedManufactureSubsystem = jobsCompletedManufactureSubsystem;
    return this;
  }

   /**
   * jobs_completed_manufacture_subsystem integer
   * @return jobsCompletedManufactureSubsystem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_subsystem integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SUBSYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureSubsystem() {
    return jobsCompletedManufactureSubsystem;
  }


  public void setJobsCompletedManufactureSubsystem(Long jobsCompletedManufactureSubsystem) {
    this.jobsCompletedManufactureSubsystem = jobsCompletedManufactureSubsystem;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedManufactureSubsystemQuantity(Long jobsCompletedManufactureSubsystemQuantity) {
    
    this.jobsCompletedManufactureSubsystemQuantity = jobsCompletedManufactureSubsystemQuantity;
    return this;
  }

   /**
   * jobs_completed_manufacture_subsystem_quantity integer
   * @return jobsCompletedManufactureSubsystemQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_manufacture_subsystem_quantity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MANUFACTURE_SUBSYSTEM_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedManufactureSubsystemQuantity() {
    return jobsCompletedManufactureSubsystemQuantity;
  }


  public void setJobsCompletedManufactureSubsystemQuantity(Long jobsCompletedManufactureSubsystemQuantity) {
    this.jobsCompletedManufactureSubsystemQuantity = jobsCompletedManufactureSubsystemQuantity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedMaterialProductivity(Long jobsCompletedMaterialProductivity) {
    
    this.jobsCompletedMaterialProductivity = jobsCompletedMaterialProductivity;
    return this;
  }

   /**
   * jobs_completed_material_productivity integer
   * @return jobsCompletedMaterialProductivity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_material_productivity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_MATERIAL_PRODUCTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedMaterialProductivity() {
    return jobsCompletedMaterialProductivity;
  }


  public void setJobsCompletedMaterialProductivity(Long jobsCompletedMaterialProductivity) {
    this.jobsCompletedMaterialProductivity = jobsCompletedMaterialProductivity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsCompletedTimeProductivity(Long jobsCompletedTimeProductivity) {
    
    this.jobsCompletedTimeProductivity = jobsCompletedTimeProductivity;
    return this;
  }

   /**
   * jobs_completed_time_productivity integer
   * @return jobsCompletedTimeProductivity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_completed_time_productivity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_COMPLETED_TIME_PRODUCTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsCompletedTimeProductivity() {
    return jobsCompletedTimeProductivity;
  }


  public void setJobsCompletedTimeProductivity(Long jobsCompletedTimeProductivity) {
    this.jobsCompletedTimeProductivity = jobsCompletedTimeProductivity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsStartedCopyBlueprint(Long jobsStartedCopyBlueprint) {
    
    this.jobsStartedCopyBlueprint = jobsStartedCopyBlueprint;
    return this;
  }

   /**
   * jobs_started_copy_blueprint integer
   * @return jobsStartedCopyBlueprint
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_started_copy_blueprint integer")
  @JsonProperty(JSON_PROPERTY_JOBS_STARTED_COPY_BLUEPRINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsStartedCopyBlueprint() {
    return jobsStartedCopyBlueprint;
  }


  public void setJobsStartedCopyBlueprint(Long jobsStartedCopyBlueprint) {
    this.jobsStartedCopyBlueprint = jobsStartedCopyBlueprint;
  }


  public GetCharactersCharacterIdStatsIndustry jobsStartedInvention(Long jobsStartedInvention) {
    
    this.jobsStartedInvention = jobsStartedInvention;
    return this;
  }

   /**
   * jobs_started_invention integer
   * @return jobsStartedInvention
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_started_invention integer")
  @JsonProperty(JSON_PROPERTY_JOBS_STARTED_INVENTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsStartedInvention() {
    return jobsStartedInvention;
  }


  public void setJobsStartedInvention(Long jobsStartedInvention) {
    this.jobsStartedInvention = jobsStartedInvention;
  }


  public GetCharactersCharacterIdStatsIndustry jobsStartedManufacture(Long jobsStartedManufacture) {
    
    this.jobsStartedManufacture = jobsStartedManufacture;
    return this;
  }

   /**
   * jobs_started_manufacture integer
   * @return jobsStartedManufacture
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_started_manufacture integer")
  @JsonProperty(JSON_PROPERTY_JOBS_STARTED_MANUFACTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsStartedManufacture() {
    return jobsStartedManufacture;
  }


  public void setJobsStartedManufacture(Long jobsStartedManufacture) {
    this.jobsStartedManufacture = jobsStartedManufacture;
  }


  public GetCharactersCharacterIdStatsIndustry jobsStartedMaterialProductivity(Long jobsStartedMaterialProductivity) {
    
    this.jobsStartedMaterialProductivity = jobsStartedMaterialProductivity;
    return this;
  }

   /**
   * jobs_started_material_productivity integer
   * @return jobsStartedMaterialProductivity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_started_material_productivity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_STARTED_MATERIAL_PRODUCTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsStartedMaterialProductivity() {
    return jobsStartedMaterialProductivity;
  }


  public void setJobsStartedMaterialProductivity(Long jobsStartedMaterialProductivity) {
    this.jobsStartedMaterialProductivity = jobsStartedMaterialProductivity;
  }


  public GetCharactersCharacterIdStatsIndustry jobsStartedTimeProductivity(Long jobsStartedTimeProductivity) {
    
    this.jobsStartedTimeProductivity = jobsStartedTimeProductivity;
    return this;
  }

   /**
   * jobs_started_time_productivity integer
   * @return jobsStartedTimeProductivity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "jobs_started_time_productivity integer")
  @JsonProperty(JSON_PROPERTY_JOBS_STARTED_TIME_PRODUCTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getJobsStartedTimeProductivity() {
    return jobsStartedTimeProductivity;
  }


  public void setJobsStartedTimeProductivity(Long jobsStartedTimeProductivity) {
    this.jobsStartedTimeProductivity = jobsStartedTimeProductivity;
  }


  public GetCharactersCharacterIdStatsIndustry reprocessItem(Long reprocessItem) {
    
    this.reprocessItem = reprocessItem;
    return this;
  }

   /**
   * reprocess_item integer
   * @return reprocessItem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "reprocess_item integer")
  @JsonProperty(JSON_PROPERTY_REPROCESS_ITEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getReprocessItem() {
    return reprocessItem;
  }


  public void setReprocessItem(Long reprocessItem) {
    this.reprocessItem = reprocessItem;
  }


  public GetCharactersCharacterIdStatsIndustry reprocessItemQuantity(Long reprocessItemQuantity) {
    
    this.reprocessItemQuantity = reprocessItemQuantity;
    return this;
  }

   /**
   * reprocess_item_quantity integer
   * @return reprocessItemQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "reprocess_item_quantity integer")
  @JsonProperty(JSON_PROPERTY_REPROCESS_ITEM_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getReprocessItemQuantity() {
    return reprocessItemQuantity;
  }


  public void setReprocessItemQuantity(Long reprocessItemQuantity) {
    this.reprocessItemQuantity = reprocessItemQuantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdStatsIndustry getCharactersCharacterIdStatsIndustry = (GetCharactersCharacterIdStatsIndustry) o;
    return Objects.equals(this.hackingSuccesses, getCharactersCharacterIdStatsIndustry.hackingSuccesses) &&
        Objects.equals(this.jobsCancelled, getCharactersCharacterIdStatsIndustry.jobsCancelled) &&
        Objects.equals(this.jobsCompletedCopyBlueprint, getCharactersCharacterIdStatsIndustry.jobsCompletedCopyBlueprint) &&
        Objects.equals(this.jobsCompletedInvention, getCharactersCharacterIdStatsIndustry.jobsCompletedInvention) &&
        Objects.equals(this.jobsCompletedManufacture, getCharactersCharacterIdStatsIndustry.jobsCompletedManufacture) &&
        Objects.equals(this.jobsCompletedManufactureAsteroid, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureAsteroid) &&
        Objects.equals(this.jobsCompletedManufactureAsteroidQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureAsteroidQuantity) &&
        Objects.equals(this.jobsCompletedManufactureCharge, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureCharge) &&
        Objects.equals(this.jobsCompletedManufactureChargeQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureChargeQuantity) &&
        Objects.equals(this.jobsCompletedManufactureCommodity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureCommodity) &&
        Objects.equals(this.jobsCompletedManufactureCommodityQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureCommodityQuantity) &&
        Objects.equals(this.jobsCompletedManufactureDeployable, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureDeployable) &&
        Objects.equals(this.jobsCompletedManufactureDeployableQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureDeployableQuantity) &&
        Objects.equals(this.jobsCompletedManufactureDrone, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureDrone) &&
        Objects.equals(this.jobsCompletedManufactureDroneQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureDroneQuantity) &&
        Objects.equals(this.jobsCompletedManufactureImplant, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureImplant) &&
        Objects.equals(this.jobsCompletedManufactureImplantQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureImplantQuantity) &&
        Objects.equals(this.jobsCompletedManufactureModule, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureModule) &&
        Objects.equals(this.jobsCompletedManufactureModuleQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureModuleQuantity) &&
        Objects.equals(this.jobsCompletedManufactureOther, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureOther) &&
        Objects.equals(this.jobsCompletedManufactureOtherQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureOtherQuantity) &&
        Objects.equals(this.jobsCompletedManufactureShip, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureShip) &&
        Objects.equals(this.jobsCompletedManufactureShipQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureShipQuantity) &&
        Objects.equals(this.jobsCompletedManufactureStructure, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureStructure) &&
        Objects.equals(this.jobsCompletedManufactureStructureQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureStructureQuantity) &&
        Objects.equals(this.jobsCompletedManufactureSubsystem, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureSubsystem) &&
        Objects.equals(this.jobsCompletedManufactureSubsystemQuantity, getCharactersCharacterIdStatsIndustry.jobsCompletedManufactureSubsystemQuantity) &&
        Objects.equals(this.jobsCompletedMaterialProductivity, getCharactersCharacterIdStatsIndustry.jobsCompletedMaterialProductivity) &&
        Objects.equals(this.jobsCompletedTimeProductivity, getCharactersCharacterIdStatsIndustry.jobsCompletedTimeProductivity) &&
        Objects.equals(this.jobsStartedCopyBlueprint, getCharactersCharacterIdStatsIndustry.jobsStartedCopyBlueprint) &&
        Objects.equals(this.jobsStartedInvention, getCharactersCharacterIdStatsIndustry.jobsStartedInvention) &&
        Objects.equals(this.jobsStartedManufacture, getCharactersCharacterIdStatsIndustry.jobsStartedManufacture) &&
        Objects.equals(this.jobsStartedMaterialProductivity, getCharactersCharacterIdStatsIndustry.jobsStartedMaterialProductivity) &&
        Objects.equals(this.jobsStartedTimeProductivity, getCharactersCharacterIdStatsIndustry.jobsStartedTimeProductivity) &&
        Objects.equals(this.reprocessItem, getCharactersCharacterIdStatsIndustry.reprocessItem) &&
        Objects.equals(this.reprocessItemQuantity, getCharactersCharacterIdStatsIndustry.reprocessItemQuantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hackingSuccesses, jobsCancelled, jobsCompletedCopyBlueprint, jobsCompletedInvention, jobsCompletedManufacture, jobsCompletedManufactureAsteroid, jobsCompletedManufactureAsteroidQuantity, jobsCompletedManufactureCharge, jobsCompletedManufactureChargeQuantity, jobsCompletedManufactureCommodity, jobsCompletedManufactureCommodityQuantity, jobsCompletedManufactureDeployable, jobsCompletedManufactureDeployableQuantity, jobsCompletedManufactureDrone, jobsCompletedManufactureDroneQuantity, jobsCompletedManufactureImplant, jobsCompletedManufactureImplantQuantity, jobsCompletedManufactureModule, jobsCompletedManufactureModuleQuantity, jobsCompletedManufactureOther, jobsCompletedManufactureOtherQuantity, jobsCompletedManufactureShip, jobsCompletedManufactureShipQuantity, jobsCompletedManufactureStructure, jobsCompletedManufactureStructureQuantity, jobsCompletedManufactureSubsystem, jobsCompletedManufactureSubsystemQuantity, jobsCompletedMaterialProductivity, jobsCompletedTimeProductivity, jobsStartedCopyBlueprint, jobsStartedInvention, jobsStartedManufacture, jobsStartedMaterialProductivity, jobsStartedTimeProductivity, reprocessItem, reprocessItemQuantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdStatsIndustry {\n");
    sb.append("    hackingSuccesses: ").append(toIndentedString(hackingSuccesses)).append("\n");
    sb.append("    jobsCancelled: ").append(toIndentedString(jobsCancelled)).append("\n");
    sb.append("    jobsCompletedCopyBlueprint: ").append(toIndentedString(jobsCompletedCopyBlueprint)).append("\n");
    sb.append("    jobsCompletedInvention: ").append(toIndentedString(jobsCompletedInvention)).append("\n");
    sb.append("    jobsCompletedManufacture: ").append(toIndentedString(jobsCompletedManufacture)).append("\n");
    sb.append("    jobsCompletedManufactureAsteroid: ").append(toIndentedString(jobsCompletedManufactureAsteroid)).append("\n");
    sb.append("    jobsCompletedManufactureAsteroidQuantity: ").append(toIndentedString(jobsCompletedManufactureAsteroidQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureCharge: ").append(toIndentedString(jobsCompletedManufactureCharge)).append("\n");
    sb.append("    jobsCompletedManufactureChargeQuantity: ").append(toIndentedString(jobsCompletedManufactureChargeQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureCommodity: ").append(toIndentedString(jobsCompletedManufactureCommodity)).append("\n");
    sb.append("    jobsCompletedManufactureCommodityQuantity: ").append(toIndentedString(jobsCompletedManufactureCommodityQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureDeployable: ").append(toIndentedString(jobsCompletedManufactureDeployable)).append("\n");
    sb.append("    jobsCompletedManufactureDeployableQuantity: ").append(toIndentedString(jobsCompletedManufactureDeployableQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureDrone: ").append(toIndentedString(jobsCompletedManufactureDrone)).append("\n");
    sb.append("    jobsCompletedManufactureDroneQuantity: ").append(toIndentedString(jobsCompletedManufactureDroneQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureImplant: ").append(toIndentedString(jobsCompletedManufactureImplant)).append("\n");
    sb.append("    jobsCompletedManufactureImplantQuantity: ").append(toIndentedString(jobsCompletedManufactureImplantQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureModule: ").append(toIndentedString(jobsCompletedManufactureModule)).append("\n");
    sb.append("    jobsCompletedManufactureModuleQuantity: ").append(toIndentedString(jobsCompletedManufactureModuleQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureOther: ").append(toIndentedString(jobsCompletedManufactureOther)).append("\n");
    sb.append("    jobsCompletedManufactureOtherQuantity: ").append(toIndentedString(jobsCompletedManufactureOtherQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureShip: ").append(toIndentedString(jobsCompletedManufactureShip)).append("\n");
    sb.append("    jobsCompletedManufactureShipQuantity: ").append(toIndentedString(jobsCompletedManufactureShipQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureStructure: ").append(toIndentedString(jobsCompletedManufactureStructure)).append("\n");
    sb.append("    jobsCompletedManufactureStructureQuantity: ").append(toIndentedString(jobsCompletedManufactureStructureQuantity)).append("\n");
    sb.append("    jobsCompletedManufactureSubsystem: ").append(toIndentedString(jobsCompletedManufactureSubsystem)).append("\n");
    sb.append("    jobsCompletedManufactureSubsystemQuantity: ").append(toIndentedString(jobsCompletedManufactureSubsystemQuantity)).append("\n");
    sb.append("    jobsCompletedMaterialProductivity: ").append(toIndentedString(jobsCompletedMaterialProductivity)).append("\n");
    sb.append("    jobsCompletedTimeProductivity: ").append(toIndentedString(jobsCompletedTimeProductivity)).append("\n");
    sb.append("    jobsStartedCopyBlueprint: ").append(toIndentedString(jobsStartedCopyBlueprint)).append("\n");
    sb.append("    jobsStartedInvention: ").append(toIndentedString(jobsStartedInvention)).append("\n");
    sb.append("    jobsStartedManufacture: ").append(toIndentedString(jobsStartedManufacture)).append("\n");
    sb.append("    jobsStartedMaterialProductivity: ").append(toIndentedString(jobsStartedMaterialProductivity)).append("\n");
    sb.append("    jobsStartedTimeProductivity: ").append(toIndentedString(jobsStartedTimeProductivity)).append("\n");
    sb.append("    reprocessItem: ").append(toIndentedString(reprocessItem)).append("\n");
    sb.append("    reprocessItemQuantity: ").append(toIndentedString(reprocessItemQuantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

