/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetCorporationsCorporationIdKillmailsRecent200Ok.JSON_PROPERTY_KILLMAIL_HASH,
  GetCorporationsCorporationIdKillmailsRecent200Ok.JSON_PROPERTY_KILLMAIL_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCorporationsCorporationIdKillmailsRecent200Ok implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_KILLMAIL_HASH = "killmail_hash";
  private String killmailHash;

  public static final String JSON_PROPERTY_KILLMAIL_ID = "killmail_id";
  private Integer killmailId;


  public GetCorporationsCorporationIdKillmailsRecent200Ok killmailHash(String killmailHash) {
    
    this.killmailHash = killmailHash;
    return this;
  }

   /**
   * A hash of this killmail
   * @return killmailHash
  **/
  @ApiModelProperty(required = true, value = "A hash of this killmail")
  @JsonProperty(JSON_PROPERTY_KILLMAIL_HASH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKillmailHash() {
    return killmailHash;
  }


  public void setKillmailHash(String killmailHash) {
    this.killmailHash = killmailHash;
  }


  public GetCorporationsCorporationIdKillmailsRecent200Ok killmailId(Integer killmailId) {
    
    this.killmailId = killmailId;
    return this;
  }

   /**
   * ID of this killmail
   * @return killmailId
  **/
  @ApiModelProperty(required = true, value = "ID of this killmail")
  @JsonProperty(JSON_PROPERTY_KILLMAIL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getKillmailId() {
    return killmailId;
  }


  public void setKillmailId(Integer killmailId) {
    this.killmailId = killmailId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationsCorporationIdKillmailsRecent200Ok getCorporationsCorporationIdKillmailsRecent200Ok = (GetCorporationsCorporationIdKillmailsRecent200Ok) o;
    return Objects.equals(this.killmailHash, getCorporationsCorporationIdKillmailsRecent200Ok.killmailHash) &&
        Objects.equals(this.killmailId, getCorporationsCorporationIdKillmailsRecent200Ok.killmailId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(killmailHash, killmailId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationsCorporationIdKillmailsRecent200Ok {\n");
    sb.append("    killmailHash: ").append(toIndentedString(killmailHash)).append("\n");
    sb.append("    killmailId: ").append(toIndentedString(killmailId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

