/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetCharactersCharacterIdPortraitOk.JSON_PROPERTY_PX128X128,
  GetCharactersCharacterIdPortraitOk.JSON_PROPERTY_PX256X256,
  GetCharactersCharacterIdPortraitOk.JSON_PROPERTY_PX512X512,
  GetCharactersCharacterIdPortraitOk.JSON_PROPERTY_PX64X64
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCharactersCharacterIdPortraitOk implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_PX128X128 = "px128x128";
  private String px128x128;

  public static final String JSON_PROPERTY_PX256X256 = "px256x256";
  private String px256x256;

  public static final String JSON_PROPERTY_PX512X512 = "px512x512";
  private String px512x512;

  public static final String JSON_PROPERTY_PX64X64 = "px64x64";
  private String px64x64;


  public GetCharactersCharacterIdPortraitOk px128x128(String px128x128) {
    
    this.px128x128 = px128x128;
    return this;
  }

   /**
   * px128x128 string
   * @return px128x128
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "px128x128 string")
  @JsonProperty(JSON_PROPERTY_PX128X128)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPx128x128() {
    return px128x128;
  }


  public void setPx128x128(String px128x128) {
    this.px128x128 = px128x128;
  }


  public GetCharactersCharacterIdPortraitOk px256x256(String px256x256) {
    
    this.px256x256 = px256x256;
    return this;
  }

   /**
   * px256x256 string
   * @return px256x256
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "px256x256 string")
  @JsonProperty(JSON_PROPERTY_PX256X256)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPx256x256() {
    return px256x256;
  }


  public void setPx256x256(String px256x256) {
    this.px256x256 = px256x256;
  }


  public GetCharactersCharacterIdPortraitOk px512x512(String px512x512) {
    
    this.px512x512 = px512x512;
    return this;
  }

   /**
   * px512x512 string
   * @return px512x512
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "px512x512 string")
  @JsonProperty(JSON_PROPERTY_PX512X512)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPx512x512() {
    return px512x512;
  }


  public void setPx512x512(String px512x512) {
    this.px512x512 = px512x512;
  }


  public GetCharactersCharacterIdPortraitOk px64x64(String px64x64) {
    
    this.px64x64 = px64x64;
    return this;
  }

   /**
   * px64x64 string
   * @return px64x64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "px64x64 string")
  @JsonProperty(JSON_PROPERTY_PX64X64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPx64x64() {
    return px64x64;
  }


  public void setPx64x64(String px64x64) {
    this.px64x64 = px64x64;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCharactersCharacterIdPortraitOk getCharactersCharacterIdPortraitOk = (GetCharactersCharacterIdPortraitOk) o;
    return Objects.equals(this.px128x128, getCharactersCharacterIdPortraitOk.px128x128) &&
        Objects.equals(this.px256x256, getCharactersCharacterIdPortraitOk.px256x256) &&
        Objects.equals(this.px512x512, getCharactersCharacterIdPortraitOk.px512x512) &&
        Objects.equals(this.px64x64, getCharactersCharacterIdPortraitOk.px64x64);
  }

  @Override
  public int hashCode() {
    return Objects.hash(px128x128, px256x256, px512x512, px64x64);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCharactersCharacterIdPortraitOk {\n");
    sb.append("    px128x128: ").append(toIndentedString(px128x128)).append("\n");
    sb.append("    px256x256: ").append(toIndentedString(px256x256)).append("\n");
    sb.append("    px512x512: ").append(toIndentedString(px512x512)).append("\n");
    sb.append("    px64x64: ").append(toIndentedString(px64x64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

