/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * wallet object
 */
@ApiModel(description = "wallet object")
@JsonPropertyOrder({
  GetCorporationsCorporationIdDivisionsWalletWallet.JSON_PROPERTY_DIVISION,
  GetCorporationsCorporationIdDivisionsWalletWallet.JSON_PROPERTY_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetCorporationsCorporationIdDivisionsWalletWallet implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_DIVISION = "division";
  private Integer division;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;


  public GetCorporationsCorporationIdDivisionsWalletWallet division(Integer division) {
    
    this.division = division;
    return this;
  }

   /**
   * division integer
   * minimum: 1
   * maximum: 7
   * @return division
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "division integer")
  @JsonProperty(JSON_PROPERTY_DIVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDivision() {
    return division;
  }


  public void setDivision(Integer division) {
    this.division = division;
  }


  public GetCorporationsCorporationIdDivisionsWalletWallet name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * name string
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "name string")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCorporationsCorporationIdDivisionsWalletWallet getCorporationsCorporationIdDivisionsWalletWallet = (GetCorporationsCorporationIdDivisionsWalletWallet) o;
    return Objects.equals(this.division, getCorporationsCorporationIdDivisionsWalletWallet.division) &&
        Objects.equals(this.name, getCorporationsCorporationIdDivisionsWalletWallet.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(division, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCorporationsCorporationIdDivisionsWalletWallet {\n");
    sb.append("    division: ").append(toIndentedString(division)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

