/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * dogma_effect object
 */
@ApiModel(description = "dogma_effect object")
@JsonPropertyOrder({
  GetDogmaDynamicItemsTypeIdItemIdDogmaEffect.JSON_PROPERTY_EFFECT_ID,
  GetDogmaDynamicItemsTypeIdItemIdDogmaEffect.JSON_PROPERTY_IS_DEFAULT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetDogmaDynamicItemsTypeIdItemIdDogmaEffect implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_EFFECT_ID = "effect_id";
  private Integer effectId;

  public static final String JSON_PROPERTY_IS_DEFAULT = "is_default";
  private Boolean isDefault;


  public GetDogmaDynamicItemsTypeIdItemIdDogmaEffect effectId(Integer effectId) {
    
    this.effectId = effectId;
    return this;
  }

   /**
   * effect_id integer
   * @return effectId
  **/
  @ApiModelProperty(required = true, value = "effect_id integer")
  @JsonProperty(JSON_PROPERTY_EFFECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEffectId() {
    return effectId;
  }


  public void setEffectId(Integer effectId) {
    this.effectId = effectId;
  }


  public GetDogmaDynamicItemsTypeIdItemIdDogmaEffect isDefault(Boolean isDefault) {
    
    this.isDefault = isDefault;
    return this;
  }

   /**
   * is_default boolean
   * @return isDefault
  **/
  @ApiModelProperty(required = true, value = "is_default boolean")
  @JsonProperty(JSON_PROPERTY_IS_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getIsDefault() {
    return isDefault;
  }


  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDogmaDynamicItemsTypeIdItemIdDogmaEffect getDogmaDynamicItemsTypeIdItemIdDogmaEffect = (GetDogmaDynamicItemsTypeIdItemIdDogmaEffect) o;
    return Objects.equals(this.effectId, getDogmaDynamicItemsTypeIdItemIdDogmaEffect.effectId) &&
        Objects.equals(this.isDefault, getDogmaDynamicItemsTypeIdItemIdDogmaEffect.isDefault);
  }

  @Override
  public int hashCode() {
    return Objects.hash(effectId, isDefault);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDogmaDynamicItemsTypeIdItemIdDogmaEffect {\n");
    sb.append("    effectId: ").append(toIndentedString(effectId)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

