/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetDogmaEffectsEffectIdModifier;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_DESCRIPTION,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_DISALLOW_AUTO_REPEAT,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_DISCHARGE_ATTRIBUTE_ID,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_DISPLAY_NAME,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_DURATION_ATTRIBUTE_ID,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_EFFECT_CATEGORY,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_EFFECT_ID,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_ELECTRONIC_CHANCE,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_FALLOFF_ATTRIBUTE_ID,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_ICON_ID,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_IS_ASSISTANCE,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_IS_OFFENSIVE,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_IS_WARP_SAFE,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_MODIFIERS,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_NAME,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_POST_EXPRESSION,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_PRE_EXPRESSION,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_PUBLISHED,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_RANGE_ATTRIBUTE_ID,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_RANGE_CHANCE,
  GetDogmaEffectsEffectIdOk.JSON_PROPERTY_TRACKING_SPEED_ATTRIBUTE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetDogmaEffectsEffectIdOk implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_DISALLOW_AUTO_REPEAT = "disallow_auto_repeat";
  private Boolean disallowAutoRepeat;

  public static final String JSON_PROPERTY_DISCHARGE_ATTRIBUTE_ID = "discharge_attribute_id";
  private Integer dischargeAttributeId;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "display_name";
  private String displayName;

  public static final String JSON_PROPERTY_DURATION_ATTRIBUTE_ID = "duration_attribute_id";
  private Integer durationAttributeId;

  public static final String JSON_PROPERTY_EFFECT_CATEGORY = "effect_category";
  private Integer effectCategory;

  public static final String JSON_PROPERTY_EFFECT_ID = "effect_id";
  private Integer effectId;

  public static final String JSON_PROPERTY_ELECTRONIC_CHANCE = "electronic_chance";
  private Boolean electronicChance;

  public static final String JSON_PROPERTY_FALLOFF_ATTRIBUTE_ID = "falloff_attribute_id";
  private Integer falloffAttributeId;

  public static final String JSON_PROPERTY_ICON_ID = "icon_id";
  private Integer iconId;

  public static final String JSON_PROPERTY_IS_ASSISTANCE = "is_assistance";
  private Boolean isAssistance;

  public static final String JSON_PROPERTY_IS_OFFENSIVE = "is_offensive";
  private Boolean isOffensive;

  public static final String JSON_PROPERTY_IS_WARP_SAFE = "is_warp_safe";
  private Boolean isWarpSafe;

  public static final String JSON_PROPERTY_MODIFIERS = "modifiers";
  private List<GetDogmaEffectsEffectIdModifier> modifiers = null;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_POST_EXPRESSION = "post_expression";
  private Integer postExpression;

  public static final String JSON_PROPERTY_PRE_EXPRESSION = "pre_expression";
  private Integer preExpression;

  public static final String JSON_PROPERTY_PUBLISHED = "published";
  private Boolean published;

  public static final String JSON_PROPERTY_RANGE_ATTRIBUTE_ID = "range_attribute_id";
  private Integer rangeAttributeId;

  public static final String JSON_PROPERTY_RANGE_CHANCE = "range_chance";
  private Boolean rangeChance;

  public static final String JSON_PROPERTY_TRACKING_SPEED_ATTRIBUTE_ID = "tracking_speed_attribute_id";
  private Integer trackingSpeedAttributeId;


  public GetDogmaEffectsEffectIdOk description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * description string
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "description string")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public GetDogmaEffectsEffectIdOk disallowAutoRepeat(Boolean disallowAutoRepeat) {
    
    this.disallowAutoRepeat = disallowAutoRepeat;
    return this;
  }

   /**
   * disallow_auto_repeat boolean
   * @return disallowAutoRepeat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "disallow_auto_repeat boolean")
  @JsonProperty(JSON_PROPERTY_DISALLOW_AUTO_REPEAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDisallowAutoRepeat() {
    return disallowAutoRepeat;
  }


  public void setDisallowAutoRepeat(Boolean disallowAutoRepeat) {
    this.disallowAutoRepeat = disallowAutoRepeat;
  }


  public GetDogmaEffectsEffectIdOk dischargeAttributeId(Integer dischargeAttributeId) {
    
    this.dischargeAttributeId = dischargeAttributeId;
    return this;
  }

   /**
   * discharge_attribute_id integer
   * @return dischargeAttributeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "discharge_attribute_id integer")
  @JsonProperty(JSON_PROPERTY_DISCHARGE_ATTRIBUTE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDischargeAttributeId() {
    return dischargeAttributeId;
  }


  public void setDischargeAttributeId(Integer dischargeAttributeId) {
    this.dischargeAttributeId = dischargeAttributeId;
  }


  public GetDogmaEffectsEffectIdOk displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * display_name string
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "display_name string")
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public GetDogmaEffectsEffectIdOk durationAttributeId(Integer durationAttributeId) {
    
    this.durationAttributeId = durationAttributeId;
    return this;
  }

   /**
   * duration_attribute_id integer
   * @return durationAttributeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "duration_attribute_id integer")
  @JsonProperty(JSON_PROPERTY_DURATION_ATTRIBUTE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDurationAttributeId() {
    return durationAttributeId;
  }


  public void setDurationAttributeId(Integer durationAttributeId) {
    this.durationAttributeId = durationAttributeId;
  }


  public GetDogmaEffectsEffectIdOk effectCategory(Integer effectCategory) {
    
    this.effectCategory = effectCategory;
    return this;
  }

   /**
   * effect_category integer
   * @return effectCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "effect_category integer")
  @JsonProperty(JSON_PROPERTY_EFFECT_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEffectCategory() {
    return effectCategory;
  }


  public void setEffectCategory(Integer effectCategory) {
    this.effectCategory = effectCategory;
  }


  public GetDogmaEffectsEffectIdOk effectId(Integer effectId) {
    
    this.effectId = effectId;
    return this;
  }

   /**
   * effect_id integer
   * @return effectId
  **/
  @ApiModelProperty(required = true, value = "effect_id integer")
  @JsonProperty(JSON_PROPERTY_EFFECT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEffectId() {
    return effectId;
  }


  public void setEffectId(Integer effectId) {
    this.effectId = effectId;
  }


  public GetDogmaEffectsEffectIdOk electronicChance(Boolean electronicChance) {
    
    this.electronicChance = electronicChance;
    return this;
  }

   /**
   * electronic_chance boolean
   * @return electronicChance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "electronic_chance boolean")
  @JsonProperty(JSON_PROPERTY_ELECTRONIC_CHANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getElectronicChance() {
    return electronicChance;
  }


  public void setElectronicChance(Boolean electronicChance) {
    this.electronicChance = electronicChance;
  }


  public GetDogmaEffectsEffectIdOk falloffAttributeId(Integer falloffAttributeId) {
    
    this.falloffAttributeId = falloffAttributeId;
    return this;
  }

   /**
   * falloff_attribute_id integer
   * @return falloffAttributeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "falloff_attribute_id integer")
  @JsonProperty(JSON_PROPERTY_FALLOFF_ATTRIBUTE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFalloffAttributeId() {
    return falloffAttributeId;
  }


  public void setFalloffAttributeId(Integer falloffAttributeId) {
    this.falloffAttributeId = falloffAttributeId;
  }


  public GetDogmaEffectsEffectIdOk iconId(Integer iconId) {
    
    this.iconId = iconId;
    return this;
  }

   /**
   * icon_id integer
   * @return iconId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "icon_id integer")
  @JsonProperty(JSON_PROPERTY_ICON_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIconId() {
    return iconId;
  }


  public void setIconId(Integer iconId) {
    this.iconId = iconId;
  }


  public GetDogmaEffectsEffectIdOk isAssistance(Boolean isAssistance) {
    
    this.isAssistance = isAssistance;
    return this;
  }

   /**
   * is_assistance boolean
   * @return isAssistance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "is_assistance boolean")
  @JsonProperty(JSON_PROPERTY_IS_ASSISTANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsAssistance() {
    return isAssistance;
  }


  public void setIsAssistance(Boolean isAssistance) {
    this.isAssistance = isAssistance;
  }


  public GetDogmaEffectsEffectIdOk isOffensive(Boolean isOffensive) {
    
    this.isOffensive = isOffensive;
    return this;
  }

   /**
   * is_offensive boolean
   * @return isOffensive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "is_offensive boolean")
  @JsonProperty(JSON_PROPERTY_IS_OFFENSIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsOffensive() {
    return isOffensive;
  }


  public void setIsOffensive(Boolean isOffensive) {
    this.isOffensive = isOffensive;
  }


  public GetDogmaEffectsEffectIdOk isWarpSafe(Boolean isWarpSafe) {
    
    this.isWarpSafe = isWarpSafe;
    return this;
  }

   /**
   * is_warp_safe boolean
   * @return isWarpSafe
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "is_warp_safe boolean")
  @JsonProperty(JSON_PROPERTY_IS_WARP_SAFE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsWarpSafe() {
    return isWarpSafe;
  }


  public void setIsWarpSafe(Boolean isWarpSafe) {
    this.isWarpSafe = isWarpSafe;
  }


  public GetDogmaEffectsEffectIdOk modifiers(List<GetDogmaEffectsEffectIdModifier> modifiers) {
    
    this.modifiers = modifiers;
    return this;
  }

  public GetDogmaEffectsEffectIdOk addModifiersItem(GetDogmaEffectsEffectIdModifier modifiersItem) {
    if (this.modifiers == null) {
      this.modifiers = new ArrayList<>();
    }
    this.modifiers.add(modifiersItem);
    return this;
  }

   /**
   * modifiers array
   * @return modifiers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "modifiers array")
  @JsonProperty(JSON_PROPERTY_MODIFIERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GetDogmaEffectsEffectIdModifier> getModifiers() {
    return modifiers;
  }


  public void setModifiers(List<GetDogmaEffectsEffectIdModifier> modifiers) {
    this.modifiers = modifiers;
  }


  public GetDogmaEffectsEffectIdOk name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * name string
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "name string")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public GetDogmaEffectsEffectIdOk postExpression(Integer postExpression) {
    
    this.postExpression = postExpression;
    return this;
  }

   /**
   * post_expression integer
   * @return postExpression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "post_expression integer")
  @JsonProperty(JSON_PROPERTY_POST_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPostExpression() {
    return postExpression;
  }


  public void setPostExpression(Integer postExpression) {
    this.postExpression = postExpression;
  }


  public GetDogmaEffectsEffectIdOk preExpression(Integer preExpression) {
    
    this.preExpression = preExpression;
    return this;
  }

   /**
   * pre_expression integer
   * @return preExpression
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "pre_expression integer")
  @JsonProperty(JSON_PROPERTY_PRE_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPreExpression() {
    return preExpression;
  }


  public void setPreExpression(Integer preExpression) {
    this.preExpression = preExpression;
  }


  public GetDogmaEffectsEffectIdOk published(Boolean published) {
    
    this.published = published;
    return this;
  }

   /**
   * published boolean
   * @return published
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "published boolean")
  @JsonProperty(JSON_PROPERTY_PUBLISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPublished() {
    return published;
  }


  public void setPublished(Boolean published) {
    this.published = published;
  }


  public GetDogmaEffectsEffectIdOk rangeAttributeId(Integer rangeAttributeId) {
    
    this.rangeAttributeId = rangeAttributeId;
    return this;
  }

   /**
   * range_attribute_id integer
   * @return rangeAttributeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "range_attribute_id integer")
  @JsonProperty(JSON_PROPERTY_RANGE_ATTRIBUTE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRangeAttributeId() {
    return rangeAttributeId;
  }


  public void setRangeAttributeId(Integer rangeAttributeId) {
    this.rangeAttributeId = rangeAttributeId;
  }


  public GetDogmaEffectsEffectIdOk rangeChance(Boolean rangeChance) {
    
    this.rangeChance = rangeChance;
    return this;
  }

   /**
   * range_chance boolean
   * @return rangeChance
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "range_chance boolean")
  @JsonProperty(JSON_PROPERTY_RANGE_CHANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getRangeChance() {
    return rangeChance;
  }


  public void setRangeChance(Boolean rangeChance) {
    this.rangeChance = rangeChance;
  }


  public GetDogmaEffectsEffectIdOk trackingSpeedAttributeId(Integer trackingSpeedAttributeId) {
    
    this.trackingSpeedAttributeId = trackingSpeedAttributeId;
    return this;
  }

   /**
   * tracking_speed_attribute_id integer
   * @return trackingSpeedAttributeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "tracking_speed_attribute_id integer")
  @JsonProperty(JSON_PROPERTY_TRACKING_SPEED_ATTRIBUTE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTrackingSpeedAttributeId() {
    return trackingSpeedAttributeId;
  }


  public void setTrackingSpeedAttributeId(Integer trackingSpeedAttributeId) {
    this.trackingSpeedAttributeId = trackingSpeedAttributeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetDogmaEffectsEffectIdOk getDogmaEffectsEffectIdOk = (GetDogmaEffectsEffectIdOk) o;
    return Objects.equals(this.description, getDogmaEffectsEffectIdOk.description) &&
        Objects.equals(this.disallowAutoRepeat, getDogmaEffectsEffectIdOk.disallowAutoRepeat) &&
        Objects.equals(this.dischargeAttributeId, getDogmaEffectsEffectIdOk.dischargeAttributeId) &&
        Objects.equals(this.displayName, getDogmaEffectsEffectIdOk.displayName) &&
        Objects.equals(this.durationAttributeId, getDogmaEffectsEffectIdOk.durationAttributeId) &&
        Objects.equals(this.effectCategory, getDogmaEffectsEffectIdOk.effectCategory) &&
        Objects.equals(this.effectId, getDogmaEffectsEffectIdOk.effectId) &&
        Objects.equals(this.electronicChance, getDogmaEffectsEffectIdOk.electronicChance) &&
        Objects.equals(this.falloffAttributeId, getDogmaEffectsEffectIdOk.falloffAttributeId) &&
        Objects.equals(this.iconId, getDogmaEffectsEffectIdOk.iconId) &&
        Objects.equals(this.isAssistance, getDogmaEffectsEffectIdOk.isAssistance) &&
        Objects.equals(this.isOffensive, getDogmaEffectsEffectIdOk.isOffensive) &&
        Objects.equals(this.isWarpSafe, getDogmaEffectsEffectIdOk.isWarpSafe) &&
        Objects.equals(this.modifiers, getDogmaEffectsEffectIdOk.modifiers) &&
        Objects.equals(this.name, getDogmaEffectsEffectIdOk.name) &&
        Objects.equals(this.postExpression, getDogmaEffectsEffectIdOk.postExpression) &&
        Objects.equals(this.preExpression, getDogmaEffectsEffectIdOk.preExpression) &&
        Objects.equals(this.published, getDogmaEffectsEffectIdOk.published) &&
        Objects.equals(this.rangeAttributeId, getDogmaEffectsEffectIdOk.rangeAttributeId) &&
        Objects.equals(this.rangeChance, getDogmaEffectsEffectIdOk.rangeChance) &&
        Objects.equals(this.trackingSpeedAttributeId, getDogmaEffectsEffectIdOk.trackingSpeedAttributeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, disallowAutoRepeat, dischargeAttributeId, displayName, durationAttributeId, effectCategory, effectId, electronicChance, falloffAttributeId, iconId, isAssistance, isOffensive, isWarpSafe, modifiers, name, postExpression, preExpression, published, rangeAttributeId, rangeChance, trackingSpeedAttributeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetDogmaEffectsEffectIdOk {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    disallowAutoRepeat: ").append(toIndentedString(disallowAutoRepeat)).append("\n");
    sb.append("    dischargeAttributeId: ").append(toIndentedString(dischargeAttributeId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    durationAttributeId: ").append(toIndentedString(durationAttributeId)).append("\n");
    sb.append("    effectCategory: ").append(toIndentedString(effectCategory)).append("\n");
    sb.append("    effectId: ").append(toIndentedString(effectId)).append("\n");
    sb.append("    electronicChance: ").append(toIndentedString(electronicChance)).append("\n");
    sb.append("    falloffAttributeId: ").append(toIndentedString(falloffAttributeId)).append("\n");
    sb.append("    iconId: ").append(toIndentedString(iconId)).append("\n");
    sb.append("    isAssistance: ").append(toIndentedString(isAssistance)).append("\n");
    sb.append("    isOffensive: ").append(toIndentedString(isOffensive)).append("\n");
    sb.append("    isWarpSafe: ").append(toIndentedString(isWarpSafe)).append("\n");
    sb.append("    modifiers: ").append(toIndentedString(modifiers)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    postExpression: ").append(toIndentedString(postExpression)).append("\n");
    sb.append("    preExpression: ").append(toIndentedString(preExpression)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    rangeAttributeId: ").append(toIndentedString(rangeAttributeId)).append("\n");
    sb.append("    rangeChance: ").append(toIndentedString(rangeChance)).append("\n");
    sb.append("    trackingSpeedAttributeId: ").append(toIndentedString(trackingSpeedAttributeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

