/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * yesterday object
 */
@ApiModel(description = "yesterday object")
@JsonPropertyOrder({
  GetFwLeaderboardsCharactersYesterdayYesterday1.JSON_PROPERTY_AMOUNT,
  GetFwLeaderboardsCharactersYesterdayYesterday1.JSON_PROPERTY_CHARACTER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetFwLeaderboardsCharactersYesterdayYesterday1 implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Integer amount;

  public static final String JSON_PROPERTY_CHARACTER_ID = "character_id";
  private Integer characterId;


  public GetFwLeaderboardsCharactersYesterdayYesterday1 amount(Integer amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Amount of victory points
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Amount of victory points")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmount() {
    return amount;
  }


  public void setAmount(Integer amount) {
    this.amount = amount;
  }


  public GetFwLeaderboardsCharactersYesterdayYesterday1 characterId(Integer characterId) {
    
    this.characterId = characterId;
    return this;
  }

   /**
   * character_id integer
   * @return characterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "character_id integer")
  @JsonProperty(JSON_PROPERTY_CHARACTER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCharacterId() {
    return characterId;
  }


  public void setCharacterId(Integer characterId) {
    this.characterId = characterId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFwLeaderboardsCharactersYesterdayYesterday1 getFwLeaderboardsCharactersYesterdayYesterday1 = (GetFwLeaderboardsCharactersYesterdayYesterday1) o;
    return Objects.equals(this.amount, getFwLeaderboardsCharactersYesterdayYesterday1.amount) &&
        Objects.equals(this.characterId, getFwLeaderboardsCharactersYesterdayYesterday1.characterId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, characterId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFwLeaderboardsCharactersYesterdayYesterday1 {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    characterId: ").append(toIndentedString(characterId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

