/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetFwLeaderboardsActiveTotalActiveTotal1;
import org.openapitools.client.model.GetFwLeaderboardsLastWeekLastWeek1;
import org.openapitools.client.model.GetFwLeaderboardsYesterdayYesterday1;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Top 4 rankings of factions by victory points from yesterday, last week and in total
 */
@ApiModel(description = "Top 4 rankings of factions by victory points from yesterday, last week and in total")
@JsonPropertyOrder({
  GetFwLeaderboardsVictoryPoints.JSON_PROPERTY_ACTIVE_TOTAL,
  GetFwLeaderboardsVictoryPoints.JSON_PROPERTY_LAST_WEEK,
  GetFwLeaderboardsVictoryPoints.JSON_PROPERTY_YESTERDAY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetFwLeaderboardsVictoryPoints implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ACTIVE_TOTAL = "active_total";
  private List<GetFwLeaderboardsActiveTotalActiveTotal1> activeTotal = new ArrayList<>();

  public static final String JSON_PROPERTY_LAST_WEEK = "last_week";
  private List<GetFwLeaderboardsLastWeekLastWeek1> lastWeek = new ArrayList<>();

  public static final String JSON_PROPERTY_YESTERDAY = "yesterday";
  private List<GetFwLeaderboardsYesterdayYesterday1> yesterday = new ArrayList<>();


  public GetFwLeaderboardsVictoryPoints activeTotal(List<GetFwLeaderboardsActiveTotalActiveTotal1> activeTotal) {
    
    this.activeTotal = activeTotal;
    return this;
  }

  public GetFwLeaderboardsVictoryPoints addActiveTotalItem(GetFwLeaderboardsActiveTotalActiveTotal1 activeTotalItem) {
    this.activeTotal.add(activeTotalItem);
    return this;
  }

   /**
   * Top 4 ranking of factions active in faction warfare by total victory points. A faction is considered \&quot;active\&quot; if they have participated in faction warfare in the past 14 days
   * @return activeTotal
  **/
  @ApiModelProperty(required = true, value = "Top 4 ranking of factions active in faction warfare by total victory points. A faction is considered \"active\" if they have participated in faction warfare in the past 14 days")
  @JsonProperty(JSON_PROPERTY_ACTIVE_TOTAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GetFwLeaderboardsActiveTotalActiveTotal1> getActiveTotal() {
    return activeTotal;
  }


  public void setActiveTotal(List<GetFwLeaderboardsActiveTotalActiveTotal1> activeTotal) {
    this.activeTotal = activeTotal;
  }


  public GetFwLeaderboardsVictoryPoints lastWeek(List<GetFwLeaderboardsLastWeekLastWeek1> lastWeek) {
    
    this.lastWeek = lastWeek;
    return this;
  }

  public GetFwLeaderboardsVictoryPoints addLastWeekItem(GetFwLeaderboardsLastWeekLastWeek1 lastWeekItem) {
    this.lastWeek.add(lastWeekItem);
    return this;
  }

   /**
   * Top 4 ranking of factions by victory points in the past week
   * @return lastWeek
  **/
  @ApiModelProperty(required = true, value = "Top 4 ranking of factions by victory points in the past week")
  @JsonProperty(JSON_PROPERTY_LAST_WEEK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GetFwLeaderboardsLastWeekLastWeek1> getLastWeek() {
    return lastWeek;
  }


  public void setLastWeek(List<GetFwLeaderboardsLastWeekLastWeek1> lastWeek) {
    this.lastWeek = lastWeek;
  }


  public GetFwLeaderboardsVictoryPoints yesterday(List<GetFwLeaderboardsYesterdayYesterday1> yesterday) {
    
    this.yesterday = yesterday;
    return this;
  }

  public GetFwLeaderboardsVictoryPoints addYesterdayItem(GetFwLeaderboardsYesterdayYesterday1 yesterdayItem) {
    this.yesterday.add(yesterdayItem);
    return this;
  }

   /**
   * Top 4 ranking of factions by victory points in the past day
   * @return yesterday
  **/
  @ApiModelProperty(required = true, value = "Top 4 ranking of factions by victory points in the past day")
  @JsonProperty(JSON_PROPERTY_YESTERDAY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GetFwLeaderboardsYesterdayYesterday1> getYesterday() {
    return yesterday;
  }


  public void setYesterday(List<GetFwLeaderboardsYesterdayYesterday1> yesterday) {
    this.yesterday = yesterday;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFwLeaderboardsVictoryPoints getFwLeaderboardsVictoryPoints = (GetFwLeaderboardsVictoryPoints) o;
    return Objects.equals(this.activeTotal, getFwLeaderboardsVictoryPoints.activeTotal) &&
        Objects.equals(this.lastWeek, getFwLeaderboardsVictoryPoints.lastWeek) &&
        Objects.equals(this.yesterday, getFwLeaderboardsVictoryPoints.yesterday);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeTotal, lastWeek, yesterday);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFwLeaderboardsVictoryPoints {\n");
    sb.append("    activeTotal: ").append(toIndentedString(activeTotal)).append("\n");
    sb.append("    lastWeek: ").append(toIndentedString(lastWeek)).append("\n");
    sb.append("    yesterday: ").append(toIndentedString(yesterday)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

