/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetFleetsFleetIdWingsSquad;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetFleetsFleetIdWings200Ok.JSON_PROPERTY_ID,
  GetFleetsFleetIdWings200Ok.JSON_PROPERTY_NAME,
  GetFleetsFleetIdWings200Ok.JSON_PROPERTY_SQUADS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetFleetsFleetIdWings200Ok implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_SQUADS = "squads";
  private List<GetFleetsFleetIdWingsSquad> squads = new ArrayList<>();


  public GetFleetsFleetIdWings200Ok id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * id integer
   * @return id
  **/
  @ApiModelProperty(required = true, value = "id integer")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public GetFleetsFleetIdWings200Ok name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * name string
   * @return name
  **/
  @ApiModelProperty(required = true, value = "name string")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public GetFleetsFleetIdWings200Ok squads(List<GetFleetsFleetIdWingsSquad> squads) {
    
    this.squads = squads;
    return this;
  }

  public GetFleetsFleetIdWings200Ok addSquadsItem(GetFleetsFleetIdWingsSquad squadsItem) {
    this.squads.add(squadsItem);
    return this;
  }

   /**
   * squads array
   * @return squads
  **/
  @ApiModelProperty(required = true, value = "squads array")
  @JsonProperty(JSON_PROPERTY_SQUADS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GetFleetsFleetIdWingsSquad> getSquads() {
    return squads;
  }


  public void setSquads(List<GetFleetsFleetIdWingsSquad> squads) {
    this.squads = squads;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFleetsFleetIdWings200Ok getFleetsFleetIdWings200Ok = (GetFleetsFleetIdWings200Ok) o;
    return Objects.equals(this.id, getFleetsFleetIdWings200Ok.id) &&
        Objects.equals(this.name, getFleetsFleetIdWings200Ok.name) &&
        Objects.equals(this.squads, getFleetsFleetIdWings200Ok.squads);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, squads);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFleetsFleetIdWings200Ok {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    squads: ").append(toIndentedString(squads)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

