/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * attacker object
 */
@ApiModel(description = "attacker object")
@JsonPropertyOrder({
  GetKillmailsKillmailIdKillmailHashAttacker.JSON_PROPERTY_ALLIANCE_ID,
  GetKillmailsKillmailIdKillmailHashAttacker.JSON_PROPERTY_CHARACTER_ID,
  GetKillmailsKillmailIdKillmailHashAttacker.JSON_PROPERTY_CORPORATION_ID,
  GetKillmailsKillmailIdKillmailHashAttacker.JSON_PROPERTY_DAMAGE_DONE,
  GetKillmailsKillmailIdKillmailHashAttacker.JSON_PROPERTY_FACTION_ID,
  GetKillmailsKillmailIdKillmailHashAttacker.JSON_PROPERTY_FINAL_BLOW,
  GetKillmailsKillmailIdKillmailHashAttacker.JSON_PROPERTY_SECURITY_STATUS,
  GetKillmailsKillmailIdKillmailHashAttacker.JSON_PROPERTY_SHIP_TYPE_ID,
  GetKillmailsKillmailIdKillmailHashAttacker.JSON_PROPERTY_WEAPON_TYPE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetKillmailsKillmailIdKillmailHashAttacker implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ALLIANCE_ID = "alliance_id";
  private Integer allianceId;

  public static final String JSON_PROPERTY_CHARACTER_ID = "character_id";
  private Integer characterId;

  public static final String JSON_PROPERTY_CORPORATION_ID = "corporation_id";
  private Integer corporationId;

  public static final String JSON_PROPERTY_DAMAGE_DONE = "damage_done";
  private Integer damageDone;

  public static final String JSON_PROPERTY_FACTION_ID = "faction_id";
  private Integer factionId;

  public static final String JSON_PROPERTY_FINAL_BLOW = "final_blow";
  private Boolean finalBlow;

  public static final String JSON_PROPERTY_SECURITY_STATUS = "security_status";
  private Float securityStatus;

  public static final String JSON_PROPERTY_SHIP_TYPE_ID = "ship_type_id";
  private Integer shipTypeId;

  public static final String JSON_PROPERTY_WEAPON_TYPE_ID = "weapon_type_id";
  private Integer weaponTypeId;


  public GetKillmailsKillmailIdKillmailHashAttacker allianceId(Integer allianceId) {
    
    this.allianceId = allianceId;
    return this;
  }

   /**
   * alliance_id integer
   * @return allianceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "alliance_id integer")
  @JsonProperty(JSON_PROPERTY_ALLIANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAllianceId() {
    return allianceId;
  }


  public void setAllianceId(Integer allianceId) {
    this.allianceId = allianceId;
  }


  public GetKillmailsKillmailIdKillmailHashAttacker characterId(Integer characterId) {
    
    this.characterId = characterId;
    return this;
  }

   /**
   * character_id integer
   * @return characterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "character_id integer")
  @JsonProperty(JSON_PROPERTY_CHARACTER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCharacterId() {
    return characterId;
  }


  public void setCharacterId(Integer characterId) {
    this.characterId = characterId;
  }


  public GetKillmailsKillmailIdKillmailHashAttacker corporationId(Integer corporationId) {
    
    this.corporationId = corporationId;
    return this;
  }

   /**
   * corporation_id integer
   * @return corporationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "corporation_id integer")
  @JsonProperty(JSON_PROPERTY_CORPORATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCorporationId() {
    return corporationId;
  }


  public void setCorporationId(Integer corporationId) {
    this.corporationId = corporationId;
  }


  public GetKillmailsKillmailIdKillmailHashAttacker damageDone(Integer damageDone) {
    
    this.damageDone = damageDone;
    return this;
  }

   /**
   * damage_done integer
   * @return damageDone
  **/
  @ApiModelProperty(required = true, value = "damage_done integer")
  @JsonProperty(JSON_PROPERTY_DAMAGE_DONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDamageDone() {
    return damageDone;
  }


  public void setDamageDone(Integer damageDone) {
    this.damageDone = damageDone;
  }


  public GetKillmailsKillmailIdKillmailHashAttacker factionId(Integer factionId) {
    
    this.factionId = factionId;
    return this;
  }

   /**
   * faction_id integer
   * @return factionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "faction_id integer")
  @JsonProperty(JSON_PROPERTY_FACTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFactionId() {
    return factionId;
  }


  public void setFactionId(Integer factionId) {
    this.factionId = factionId;
  }


  public GetKillmailsKillmailIdKillmailHashAttacker finalBlow(Boolean finalBlow) {
    
    this.finalBlow = finalBlow;
    return this;
  }

   /**
   * Was the attacker the one to achieve the final blow 
   * @return finalBlow
  **/
  @ApiModelProperty(required = true, value = "Was the attacker the one to achieve the final blow ")
  @JsonProperty(JSON_PROPERTY_FINAL_BLOW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getFinalBlow() {
    return finalBlow;
  }


  public void setFinalBlow(Boolean finalBlow) {
    this.finalBlow = finalBlow;
  }


  public GetKillmailsKillmailIdKillmailHashAttacker securityStatus(Float securityStatus) {
    
    this.securityStatus = securityStatus;
    return this;
  }

   /**
   * Security status for the attacker 
   * @return securityStatus
  **/
  @ApiModelProperty(required = true, value = "Security status for the attacker ")
  @JsonProperty(JSON_PROPERTY_SECURITY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Float getSecurityStatus() {
    return securityStatus;
  }


  public void setSecurityStatus(Float securityStatus) {
    this.securityStatus = securityStatus;
  }


  public GetKillmailsKillmailIdKillmailHashAttacker shipTypeId(Integer shipTypeId) {
    
    this.shipTypeId = shipTypeId;
    return this;
  }

   /**
   * What ship was the attacker flying 
   * @return shipTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "What ship was the attacker flying ")
  @JsonProperty(JSON_PROPERTY_SHIP_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getShipTypeId() {
    return shipTypeId;
  }


  public void setShipTypeId(Integer shipTypeId) {
    this.shipTypeId = shipTypeId;
  }


  public GetKillmailsKillmailIdKillmailHashAttacker weaponTypeId(Integer weaponTypeId) {
    
    this.weaponTypeId = weaponTypeId;
    return this;
  }

   /**
   * What weapon was used by the attacker for the kill 
   * @return weaponTypeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "What weapon was used by the attacker for the kill ")
  @JsonProperty(JSON_PROPERTY_WEAPON_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWeaponTypeId() {
    return weaponTypeId;
  }


  public void setWeaponTypeId(Integer weaponTypeId) {
    this.weaponTypeId = weaponTypeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetKillmailsKillmailIdKillmailHashAttacker getKillmailsKillmailIdKillmailHashAttacker = (GetKillmailsKillmailIdKillmailHashAttacker) o;
    return Objects.equals(this.allianceId, getKillmailsKillmailIdKillmailHashAttacker.allianceId) &&
        Objects.equals(this.characterId, getKillmailsKillmailIdKillmailHashAttacker.characterId) &&
        Objects.equals(this.corporationId, getKillmailsKillmailIdKillmailHashAttacker.corporationId) &&
        Objects.equals(this.damageDone, getKillmailsKillmailIdKillmailHashAttacker.damageDone) &&
        Objects.equals(this.factionId, getKillmailsKillmailIdKillmailHashAttacker.factionId) &&
        Objects.equals(this.finalBlow, getKillmailsKillmailIdKillmailHashAttacker.finalBlow) &&
        Objects.equals(this.securityStatus, getKillmailsKillmailIdKillmailHashAttacker.securityStatus) &&
        Objects.equals(this.shipTypeId, getKillmailsKillmailIdKillmailHashAttacker.shipTypeId) &&
        Objects.equals(this.weaponTypeId, getKillmailsKillmailIdKillmailHashAttacker.weaponTypeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allianceId, characterId, corporationId, damageDone, factionId, finalBlow, securityStatus, shipTypeId, weaponTypeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetKillmailsKillmailIdKillmailHashAttacker {\n");
    sb.append("    allianceId: ").append(toIndentedString(allianceId)).append("\n");
    sb.append("    characterId: ").append(toIndentedString(characterId)).append("\n");
    sb.append("    corporationId: ").append(toIndentedString(corporationId)).append("\n");
    sb.append("    damageDone: ").append(toIndentedString(damageDone)).append("\n");
    sb.append("    factionId: ").append(toIndentedString(factionId)).append("\n");
    sb.append("    finalBlow: ").append(toIndentedString(finalBlow)).append("\n");
    sb.append("    securityStatus: ").append(toIndentedString(securityStatus)).append("\n");
    sb.append("    shipTypeId: ").append(toIndentedString(shipTypeId)).append("\n");
    sb.append("    weaponTypeId: ").append(toIndentedString(weaponTypeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

