/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * item object
 */
@ApiModel(description = "item object")
@JsonPropertyOrder({
  GetKillmailsKillmailIdKillmailHashItemsItem.JSON_PROPERTY_FLAG,
  GetKillmailsKillmailIdKillmailHashItemsItem.JSON_PROPERTY_ITEM_TYPE_ID,
  GetKillmailsKillmailIdKillmailHashItemsItem.JSON_PROPERTY_QUANTITY_DESTROYED,
  GetKillmailsKillmailIdKillmailHashItemsItem.JSON_PROPERTY_QUANTITY_DROPPED,
  GetKillmailsKillmailIdKillmailHashItemsItem.JSON_PROPERTY_SINGLETON
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetKillmailsKillmailIdKillmailHashItemsItem implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_FLAG = "flag";
  private Integer flag;

  public static final String JSON_PROPERTY_ITEM_TYPE_ID = "item_type_id";
  private Integer itemTypeId;

  public static final String JSON_PROPERTY_QUANTITY_DESTROYED = "quantity_destroyed";
  private Long quantityDestroyed;

  public static final String JSON_PROPERTY_QUANTITY_DROPPED = "quantity_dropped";
  private Long quantityDropped;

  public static final String JSON_PROPERTY_SINGLETON = "singleton";
  private Integer singleton;


  public GetKillmailsKillmailIdKillmailHashItemsItem flag(Integer flag) {
    
    this.flag = flag;
    return this;
  }

   /**
   * flag integer
   * @return flag
  **/
  @ApiModelProperty(required = true, value = "flag integer")
  @JsonProperty(JSON_PROPERTY_FLAG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFlag() {
    return flag;
  }


  public void setFlag(Integer flag) {
    this.flag = flag;
  }


  public GetKillmailsKillmailIdKillmailHashItemsItem itemTypeId(Integer itemTypeId) {
    
    this.itemTypeId = itemTypeId;
    return this;
  }

   /**
   * item_type_id integer
   * @return itemTypeId
  **/
  @ApiModelProperty(required = true, value = "item_type_id integer")
  @JsonProperty(JSON_PROPERTY_ITEM_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getItemTypeId() {
    return itemTypeId;
  }


  public void setItemTypeId(Integer itemTypeId) {
    this.itemTypeId = itemTypeId;
  }


  public GetKillmailsKillmailIdKillmailHashItemsItem quantityDestroyed(Long quantityDestroyed) {
    
    this.quantityDestroyed = quantityDestroyed;
    return this;
  }

   /**
   * quantity_destroyed integer
   * @return quantityDestroyed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "quantity_destroyed integer")
  @JsonProperty(JSON_PROPERTY_QUANTITY_DESTROYED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getQuantityDestroyed() {
    return quantityDestroyed;
  }


  public void setQuantityDestroyed(Long quantityDestroyed) {
    this.quantityDestroyed = quantityDestroyed;
  }


  public GetKillmailsKillmailIdKillmailHashItemsItem quantityDropped(Long quantityDropped) {
    
    this.quantityDropped = quantityDropped;
    return this;
  }

   /**
   * quantity_dropped integer
   * @return quantityDropped
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "quantity_dropped integer")
  @JsonProperty(JSON_PROPERTY_QUANTITY_DROPPED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getQuantityDropped() {
    return quantityDropped;
  }


  public void setQuantityDropped(Long quantityDropped) {
    this.quantityDropped = quantityDropped;
  }


  public GetKillmailsKillmailIdKillmailHashItemsItem singleton(Integer singleton) {
    
    this.singleton = singleton;
    return this;
  }

   /**
   * singleton integer
   * @return singleton
  **/
  @ApiModelProperty(required = true, value = "singleton integer")
  @JsonProperty(JSON_PROPERTY_SINGLETON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSingleton() {
    return singleton;
  }


  public void setSingleton(Integer singleton) {
    this.singleton = singleton;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetKillmailsKillmailIdKillmailHashItemsItem getKillmailsKillmailIdKillmailHashItemsItem = (GetKillmailsKillmailIdKillmailHashItemsItem) o;
    return Objects.equals(this.flag, getKillmailsKillmailIdKillmailHashItemsItem.flag) &&
        Objects.equals(this.itemTypeId, getKillmailsKillmailIdKillmailHashItemsItem.itemTypeId) &&
        Objects.equals(this.quantityDestroyed, getKillmailsKillmailIdKillmailHashItemsItem.quantityDestroyed) &&
        Objects.equals(this.quantityDropped, getKillmailsKillmailIdKillmailHashItemsItem.quantityDropped) &&
        Objects.equals(this.singleton, getKillmailsKillmailIdKillmailHashItemsItem.singleton);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flag, itemTypeId, quantityDestroyed, quantityDropped, singleton);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetKillmailsKillmailIdKillmailHashItemsItem {\n");
    sb.append("    flag: ").append(toIndentedString(flag)).append("\n");
    sb.append("    itemTypeId: ").append(toIndentedString(itemTypeId)).append("\n");
    sb.append("    quantityDestroyed: ").append(toIndentedString(quantityDestroyed)).append("\n");
    sb.append("    quantityDropped: ").append(toIndentedString(quantityDropped)).append("\n");
    sb.append("    singleton: ").append(toIndentedString(singleton)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

