/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetLoyaltyStoresCorporationIdOffersRequiredItem;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetLoyaltyStoresCorporationIdOffers200Ok.JSON_PROPERTY_AK_COST,
  GetLoyaltyStoresCorporationIdOffers200Ok.JSON_PROPERTY_ISK_COST,
  GetLoyaltyStoresCorporationIdOffers200Ok.JSON_PROPERTY_LP_COST,
  GetLoyaltyStoresCorporationIdOffers200Ok.JSON_PROPERTY_OFFER_ID,
  GetLoyaltyStoresCorporationIdOffers200Ok.JSON_PROPERTY_QUANTITY,
  GetLoyaltyStoresCorporationIdOffers200Ok.JSON_PROPERTY_REQUIRED_ITEMS,
  GetLoyaltyStoresCorporationIdOffers200Ok.JSON_PROPERTY_TYPE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetLoyaltyStoresCorporationIdOffers200Ok implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_AK_COST = "ak_cost";
  private Integer akCost;

  public static final String JSON_PROPERTY_ISK_COST = "isk_cost";
  private Long iskCost;

  public static final String JSON_PROPERTY_LP_COST = "lp_cost";
  private Integer lpCost;

  public static final String JSON_PROPERTY_OFFER_ID = "offer_id";
  private Integer offerId;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Integer quantity;

  public static final String JSON_PROPERTY_REQUIRED_ITEMS = "required_items";
  private List<GetLoyaltyStoresCorporationIdOffersRequiredItem> requiredItems = new ArrayList<>();

  public static final String JSON_PROPERTY_TYPE_ID = "type_id";
  private Integer typeId;


  public GetLoyaltyStoresCorporationIdOffers200Ok akCost(Integer akCost) {
    
    this.akCost = akCost;
    return this;
  }

   /**
   * Analysis kredit cost
   * @return akCost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Analysis kredit cost")
  @JsonProperty(JSON_PROPERTY_AK_COST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAkCost() {
    return akCost;
  }


  public void setAkCost(Integer akCost) {
    this.akCost = akCost;
  }


  public GetLoyaltyStoresCorporationIdOffers200Ok iskCost(Long iskCost) {
    
    this.iskCost = iskCost;
    return this;
  }

   /**
   * isk_cost integer
   * @return iskCost
  **/
  @ApiModelProperty(required = true, value = "isk_cost integer")
  @JsonProperty(JSON_PROPERTY_ISK_COST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getIskCost() {
    return iskCost;
  }


  public void setIskCost(Long iskCost) {
    this.iskCost = iskCost;
  }


  public GetLoyaltyStoresCorporationIdOffers200Ok lpCost(Integer lpCost) {
    
    this.lpCost = lpCost;
    return this;
  }

   /**
   * lp_cost integer
   * @return lpCost
  **/
  @ApiModelProperty(required = true, value = "lp_cost integer")
  @JsonProperty(JSON_PROPERTY_LP_COST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getLpCost() {
    return lpCost;
  }


  public void setLpCost(Integer lpCost) {
    this.lpCost = lpCost;
  }


  public GetLoyaltyStoresCorporationIdOffers200Ok offerId(Integer offerId) {
    
    this.offerId = offerId;
    return this;
  }

   /**
   * offer_id integer
   * @return offerId
  **/
  @ApiModelProperty(required = true, value = "offer_id integer")
  @JsonProperty(JSON_PROPERTY_OFFER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getOfferId() {
    return offerId;
  }


  public void setOfferId(Integer offerId) {
    this.offerId = offerId;
  }


  public GetLoyaltyStoresCorporationIdOffers200Ok quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * quantity integer
   * @return quantity
  **/
  @ApiModelProperty(required = true, value = "quantity integer")
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getQuantity() {
    return quantity;
  }


  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public GetLoyaltyStoresCorporationIdOffers200Ok requiredItems(List<GetLoyaltyStoresCorporationIdOffersRequiredItem> requiredItems) {
    
    this.requiredItems = requiredItems;
    return this;
  }

  public GetLoyaltyStoresCorporationIdOffers200Ok addRequiredItemsItem(GetLoyaltyStoresCorporationIdOffersRequiredItem requiredItemsItem) {
    this.requiredItems.add(requiredItemsItem);
    return this;
  }

   /**
   * required_items array
   * @return requiredItems
  **/
  @ApiModelProperty(required = true, value = "required_items array")
  @JsonProperty(JSON_PROPERTY_REQUIRED_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GetLoyaltyStoresCorporationIdOffersRequiredItem> getRequiredItems() {
    return requiredItems;
  }


  public void setRequiredItems(List<GetLoyaltyStoresCorporationIdOffersRequiredItem> requiredItems) {
    this.requiredItems = requiredItems;
  }


  public GetLoyaltyStoresCorporationIdOffers200Ok typeId(Integer typeId) {
    
    this.typeId = typeId;
    return this;
  }

   /**
   * type_id integer
   * @return typeId
  **/
  @ApiModelProperty(required = true, value = "type_id integer")
  @JsonProperty(JSON_PROPERTY_TYPE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTypeId() {
    return typeId;
  }


  public void setTypeId(Integer typeId) {
    this.typeId = typeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetLoyaltyStoresCorporationIdOffers200Ok getLoyaltyStoresCorporationIdOffers200Ok = (GetLoyaltyStoresCorporationIdOffers200Ok) o;
    return Objects.equals(this.akCost, getLoyaltyStoresCorporationIdOffers200Ok.akCost) &&
        Objects.equals(this.iskCost, getLoyaltyStoresCorporationIdOffers200Ok.iskCost) &&
        Objects.equals(this.lpCost, getLoyaltyStoresCorporationIdOffers200Ok.lpCost) &&
        Objects.equals(this.offerId, getLoyaltyStoresCorporationIdOffers200Ok.offerId) &&
        Objects.equals(this.quantity, getLoyaltyStoresCorporationIdOffers200Ok.quantity) &&
        Objects.equals(this.requiredItems, getLoyaltyStoresCorporationIdOffers200Ok.requiredItems) &&
        Objects.equals(this.typeId, getLoyaltyStoresCorporationIdOffers200Ok.typeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(akCost, iskCost, lpCost, offerId, quantity, requiredItems, typeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetLoyaltyStoresCorporationIdOffers200Ok {\n");
    sb.append("    akCost: ").append(toIndentedString(akCost)).append("\n");
    sb.append("    iskCost: ").append(toIndentedString(iskCost)).append("\n");
    sb.append("    lpCost: ").append(toIndentedString(lpCost)).append("\n");
    sb.append("    offerId: ").append(toIndentedString(offerId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    requiredItems: ").append(toIndentedString(requiredItems)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

