/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetUniverseGraphicsGraphicIdOk.JSON_PROPERTY_COLLISION_FILE,
  GetUniverseGraphicsGraphicIdOk.JSON_PROPERTY_GRAPHIC_FILE,
  GetUniverseGraphicsGraphicIdOk.JSON_PROPERTY_GRAPHIC_ID,
  GetUniverseGraphicsGraphicIdOk.JSON_PROPERTY_ICON_FOLDER,
  GetUniverseGraphicsGraphicIdOk.JSON_PROPERTY_SOF_DNA,
  GetUniverseGraphicsGraphicIdOk.JSON_PROPERTY_SOF_FATION_NAME,
  GetUniverseGraphicsGraphicIdOk.JSON_PROPERTY_SOF_HULL_NAME,
  GetUniverseGraphicsGraphicIdOk.JSON_PROPERTY_SOF_RACE_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetUniverseGraphicsGraphicIdOk implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_COLLISION_FILE = "collision_file";
  private String collisionFile;

  public static final String JSON_PROPERTY_GRAPHIC_FILE = "graphic_file";
  private String graphicFile;

  public static final String JSON_PROPERTY_GRAPHIC_ID = "graphic_id";
  private Integer graphicId;

  public static final String JSON_PROPERTY_ICON_FOLDER = "icon_folder";
  private String iconFolder;

  public static final String JSON_PROPERTY_SOF_DNA = "sof_dna";
  private String sofDna;

  public static final String JSON_PROPERTY_SOF_FATION_NAME = "sof_fation_name";
  private String sofFationName;

  public static final String JSON_PROPERTY_SOF_HULL_NAME = "sof_hull_name";
  private String sofHullName;

  public static final String JSON_PROPERTY_SOF_RACE_NAME = "sof_race_name";
  private String sofRaceName;


  public GetUniverseGraphicsGraphicIdOk collisionFile(String collisionFile) {
    
    this.collisionFile = collisionFile;
    return this;
  }

   /**
   * collision_file string
   * @return collisionFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "collision_file string")
  @JsonProperty(JSON_PROPERTY_COLLISION_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCollisionFile() {
    return collisionFile;
  }


  public void setCollisionFile(String collisionFile) {
    this.collisionFile = collisionFile;
  }


  public GetUniverseGraphicsGraphicIdOk graphicFile(String graphicFile) {
    
    this.graphicFile = graphicFile;
    return this;
  }

   /**
   * graphic_file string
   * @return graphicFile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "graphic_file string")
  @JsonProperty(JSON_PROPERTY_GRAPHIC_FILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGraphicFile() {
    return graphicFile;
  }


  public void setGraphicFile(String graphicFile) {
    this.graphicFile = graphicFile;
  }


  public GetUniverseGraphicsGraphicIdOk graphicId(Integer graphicId) {
    
    this.graphicId = graphicId;
    return this;
  }

   /**
   * graphic_id integer
   * @return graphicId
  **/
  @ApiModelProperty(required = true, value = "graphic_id integer")
  @JsonProperty(JSON_PROPERTY_GRAPHIC_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getGraphicId() {
    return graphicId;
  }


  public void setGraphicId(Integer graphicId) {
    this.graphicId = graphicId;
  }


  public GetUniverseGraphicsGraphicIdOk iconFolder(String iconFolder) {
    
    this.iconFolder = iconFolder;
    return this;
  }

   /**
   * icon_folder string
   * @return iconFolder
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "icon_folder string")
  @JsonProperty(JSON_PROPERTY_ICON_FOLDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIconFolder() {
    return iconFolder;
  }


  public void setIconFolder(String iconFolder) {
    this.iconFolder = iconFolder;
  }


  public GetUniverseGraphicsGraphicIdOk sofDna(String sofDna) {
    
    this.sofDna = sofDna;
    return this;
  }

   /**
   * sof_dna string
   * @return sofDna
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "sof_dna string")
  @JsonProperty(JSON_PROPERTY_SOF_DNA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSofDna() {
    return sofDna;
  }


  public void setSofDna(String sofDna) {
    this.sofDna = sofDna;
  }


  public GetUniverseGraphicsGraphicIdOk sofFationName(String sofFationName) {
    
    this.sofFationName = sofFationName;
    return this;
  }

   /**
   * sof_fation_name string
   * @return sofFationName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "sof_fation_name string")
  @JsonProperty(JSON_PROPERTY_SOF_FATION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSofFationName() {
    return sofFationName;
  }


  public void setSofFationName(String sofFationName) {
    this.sofFationName = sofFationName;
  }


  public GetUniverseGraphicsGraphicIdOk sofHullName(String sofHullName) {
    
    this.sofHullName = sofHullName;
    return this;
  }

   /**
   * sof_hull_name string
   * @return sofHullName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "sof_hull_name string")
  @JsonProperty(JSON_PROPERTY_SOF_HULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSofHullName() {
    return sofHullName;
  }


  public void setSofHullName(String sofHullName) {
    this.sofHullName = sofHullName;
  }


  public GetUniverseGraphicsGraphicIdOk sofRaceName(String sofRaceName) {
    
    this.sofRaceName = sofRaceName;
    return this;
  }

   /**
   * sof_race_name string
   * @return sofRaceName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "sof_race_name string")
  @JsonProperty(JSON_PROPERTY_SOF_RACE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSofRaceName() {
    return sofRaceName;
  }


  public void setSofRaceName(String sofRaceName) {
    this.sofRaceName = sofRaceName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUniverseGraphicsGraphicIdOk getUniverseGraphicsGraphicIdOk = (GetUniverseGraphicsGraphicIdOk) o;
    return Objects.equals(this.collisionFile, getUniverseGraphicsGraphicIdOk.collisionFile) &&
        Objects.equals(this.graphicFile, getUniverseGraphicsGraphicIdOk.graphicFile) &&
        Objects.equals(this.graphicId, getUniverseGraphicsGraphicIdOk.graphicId) &&
        Objects.equals(this.iconFolder, getUniverseGraphicsGraphicIdOk.iconFolder) &&
        Objects.equals(this.sofDna, getUniverseGraphicsGraphicIdOk.sofDna) &&
        Objects.equals(this.sofFationName, getUniverseGraphicsGraphicIdOk.sofFationName) &&
        Objects.equals(this.sofHullName, getUniverseGraphicsGraphicIdOk.sofHullName) &&
        Objects.equals(this.sofRaceName, getUniverseGraphicsGraphicIdOk.sofRaceName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(collisionFile, graphicFile, graphicId, iconFolder, sofDna, sofFationName, sofHullName, sofRaceName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUniverseGraphicsGraphicIdOk {\n");
    sb.append("    collisionFile: ").append(toIndentedString(collisionFile)).append("\n");
    sb.append("    graphicFile: ").append(toIndentedString(graphicFile)).append("\n");
    sb.append("    graphicId: ").append(toIndentedString(graphicId)).append("\n");
    sb.append("    iconFolder: ").append(toIndentedString(iconFolder)).append("\n");
    sb.append("    sofDna: ").append(toIndentedString(sofDna)).append("\n");
    sb.append("    sofFationName: ").append(toIndentedString(sofFationName)).append("\n");
    sb.append("    sofHullName: ").append(toIndentedString(sofHullName)).append("\n");
    sb.append("    sofRaceName: ").append(toIndentedString(sofRaceName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

