/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetUniverseSystemJumps200Ok.JSON_PROPERTY_SHIP_JUMPS,
  GetUniverseSystemJumps200Ok.JSON_PROPERTY_SYSTEM_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetUniverseSystemJumps200Ok implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_SHIP_JUMPS = "ship_jumps";
  private Integer shipJumps;

  public static final String JSON_PROPERTY_SYSTEM_ID = "system_id";
  private Integer systemId;


  public GetUniverseSystemJumps200Ok shipJumps(Integer shipJumps) {
    
    this.shipJumps = shipJumps;
    return this;
  }

   /**
   * ship_jumps integer
   * @return shipJumps
  **/
  @ApiModelProperty(required = true, value = "ship_jumps integer")
  @JsonProperty(JSON_PROPERTY_SHIP_JUMPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getShipJumps() {
    return shipJumps;
  }


  public void setShipJumps(Integer shipJumps) {
    this.shipJumps = shipJumps;
  }


  public GetUniverseSystemJumps200Ok systemId(Integer systemId) {
    
    this.systemId = systemId;
    return this;
  }

   /**
   * system_id integer
   * @return systemId
  **/
  @ApiModelProperty(required = true, value = "system_id integer")
  @JsonProperty(JSON_PROPERTY_SYSTEM_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSystemId() {
    return systemId;
  }


  public void setSystemId(Integer systemId) {
    this.systemId = systemId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUniverseSystemJumps200Ok getUniverseSystemJumps200Ok = (GetUniverseSystemJumps200Ok) o;
    return Objects.equals(this.shipJumps, getUniverseSystemJumps200Ok.shipJumps) &&
        Objects.equals(this.systemId, getUniverseSystemJumps200Ok.systemId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(shipJumps, systemId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUniverseSystemJumps200Ok {\n");
    sb.append("    shipJumps: ").append(toIndentedString(shipJumps)).append("\n");
    sb.append("    systemId: ").append(toIndentedString(systemId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

