/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetUniverseCategoriesCategoryIdOk.JSON_PROPERTY_CATEGORY_ID,
  GetUniverseCategoriesCategoryIdOk.JSON_PROPERTY_GROUPS,
  GetUniverseCategoriesCategoryIdOk.JSON_PROPERTY_NAME,
  GetUniverseCategoriesCategoryIdOk.JSON_PROPERTY_PUBLISHED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetUniverseCategoriesCategoryIdOk implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CATEGORY_ID = "category_id";
  private Integer categoryId;

  public static final String JSON_PROPERTY_GROUPS = "groups";
  private List<Integer> groups = new ArrayList<>();

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_PUBLISHED = "published";
  private Boolean published;


  public GetUniverseCategoriesCategoryIdOk categoryId(Integer categoryId) {
    
    this.categoryId = categoryId;
    return this;
  }

   /**
   * category_id integer
   * @return categoryId
  **/
  @ApiModelProperty(required = true, value = "category_id integer")
  @JsonProperty(JSON_PROPERTY_CATEGORY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCategoryId() {
    return categoryId;
  }


  public void setCategoryId(Integer categoryId) {
    this.categoryId = categoryId;
  }


  public GetUniverseCategoriesCategoryIdOk groups(List<Integer> groups) {
    
    this.groups = groups;
    return this;
  }

  public GetUniverseCategoriesCategoryIdOk addGroupsItem(Integer groupsItem) {
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * groups array
   * @return groups
  **/
  @ApiModelProperty(required = true, value = "groups array")
  @JsonProperty(JSON_PROPERTY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Integer> getGroups() {
    return groups;
  }


  public void setGroups(List<Integer> groups) {
    this.groups = groups;
  }


  public GetUniverseCategoriesCategoryIdOk name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * name string
   * @return name
  **/
  @ApiModelProperty(required = true, value = "name string")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public GetUniverseCategoriesCategoryIdOk published(Boolean published) {
    
    this.published = published;
    return this;
  }

   /**
   * published boolean
   * @return published
  **/
  @ApiModelProperty(required = true, value = "published boolean")
  @JsonProperty(JSON_PROPERTY_PUBLISHED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getPublished() {
    return published;
  }


  public void setPublished(Boolean published) {
    this.published = published;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUniverseCategoriesCategoryIdOk getUniverseCategoriesCategoryIdOk = (GetUniverseCategoriesCategoryIdOk) o;
    return Objects.equals(this.categoryId, getUniverseCategoriesCategoryIdOk.categoryId) &&
        Objects.equals(this.groups, getUniverseCategoriesCategoryIdOk.groups) &&
        Objects.equals(this.name, getUniverseCategoriesCategoryIdOk.name) &&
        Objects.equals(this.published, getUniverseCategoriesCategoryIdOk.published);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryId, groups, name, published);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUniverseCategoriesCategoryIdOk {\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

