/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.GetUniverseAsteroidBeltsAsteroidBeltIdPosition;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetUniverseAsteroidBeltsAsteroidBeltIdOk.JSON_PROPERTY_NAME,
  GetUniverseAsteroidBeltsAsteroidBeltIdOk.JSON_PROPERTY_POSITION,
  GetUniverseAsteroidBeltsAsteroidBeltIdOk.JSON_PROPERTY_SYSTEM_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetUniverseAsteroidBeltsAsteroidBeltIdOk implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_POSITION = "position";
  private GetUniverseAsteroidBeltsAsteroidBeltIdPosition position;

  public static final String JSON_PROPERTY_SYSTEM_ID = "system_id";
  private Integer systemId;


  public GetUniverseAsteroidBeltsAsteroidBeltIdOk name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * name string
   * @return name
  **/
  @ApiModelProperty(required = true, value = "name string")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public GetUniverseAsteroidBeltsAsteroidBeltIdOk position(GetUniverseAsteroidBeltsAsteroidBeltIdPosition position) {
    
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GetUniverseAsteroidBeltsAsteroidBeltIdPosition getPosition() {
    return position;
  }


  public void setPosition(GetUniverseAsteroidBeltsAsteroidBeltIdPosition position) {
    this.position = position;
  }


  public GetUniverseAsteroidBeltsAsteroidBeltIdOk systemId(Integer systemId) {
    
    this.systemId = systemId;
    return this;
  }

   /**
   * The solar system this asteroid belt is in
   * @return systemId
  **/
  @ApiModelProperty(required = true, value = "The solar system this asteroid belt is in")
  @JsonProperty(JSON_PROPERTY_SYSTEM_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSystemId() {
    return systemId;
  }


  public void setSystemId(Integer systemId) {
    this.systemId = systemId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUniverseAsteroidBeltsAsteroidBeltIdOk getUniverseAsteroidBeltsAsteroidBeltIdOk = (GetUniverseAsteroidBeltsAsteroidBeltIdOk) o;
    return Objects.equals(this.name, getUniverseAsteroidBeltsAsteroidBeltIdOk.name) &&
        Objects.equals(this.position, getUniverseAsteroidBeltsAsteroidBeltIdOk.position) &&
        Objects.equals(this.systemId, getUniverseAsteroidBeltsAsteroidBeltIdOk.systemId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, position, systemId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUniverseAsteroidBeltsAsteroidBeltIdOk {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    systemId: ").append(toIndentedString(systemId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

