/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")
@JsonPropertyOrder({
  GetUniverseSchematicsSchematicIdOk.JSON_PROPERTY_CYCLE_TIME,
  GetUniverseSchematicsSchematicIdOk.JSON_PROPERTY_SCHEMATIC_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetUniverseSchematicsSchematicIdOk implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CYCLE_TIME = "cycle_time";
  private Integer cycleTime;

  public static final String JSON_PROPERTY_SCHEMATIC_NAME = "schematic_name";
  private String schematicName;


  public GetUniverseSchematicsSchematicIdOk cycleTime(Integer cycleTime) {
    
    this.cycleTime = cycleTime;
    return this;
  }

   /**
   * Time in seconds to process a run
   * @return cycleTime
  **/
  @ApiModelProperty(required = true, value = "Time in seconds to process a run")
  @JsonProperty(JSON_PROPERTY_CYCLE_TIME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCycleTime() {
    return cycleTime;
  }


  public void setCycleTime(Integer cycleTime) {
    this.cycleTime = cycleTime;
  }


  public GetUniverseSchematicsSchematicIdOk schematicName(String schematicName) {
    
    this.schematicName = schematicName;
    return this;
  }

   /**
   * schematic_name string
   * @return schematicName
  **/
  @ApiModelProperty(required = true, value = "schematic_name string")
  @JsonProperty(JSON_PROPERTY_SCHEMATIC_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSchematicName() {
    return schematicName;
  }


  public void setSchematicName(String schematicName) {
    this.schematicName = schematicName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUniverseSchematicsSchematicIdOk getUniverseSchematicsSchematicIdOk = (GetUniverseSchematicsSchematicIdOk) o;
    return Objects.equals(this.cycleTime, getUniverseSchematicsSchematicIdOk.cycleTime) &&
        Objects.equals(this.schematicName, getUniverseSchematicsSchematicIdOk.schematicName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cycleTime, schematicName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUniverseSchematicsSchematicIdOk {\n");
    sb.append("    cycleTime: ").append(toIndentedString(cycleTime)).append("\n");
    sb.append("    schematicName: ").append(toIndentedString(schematicName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

