/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The defending corporation or alliance that declared this war, only contains either corporation_id or alliance_id
 */
@ApiModel(description = "The defending corporation or alliance that declared this war, only contains either corporation_id or alliance_id")
@JsonPropertyOrder({
  GetWarsWarIdDefender.JSON_PROPERTY_ALLIANCE_ID,
  GetWarsWarIdDefender.JSON_PROPERTY_CORPORATION_ID,
  GetWarsWarIdDefender.JSON_PROPERTY_ISK_DESTROYED,
  GetWarsWarIdDefender.JSON_PROPERTY_SHIPS_KILLED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class GetWarsWarIdDefender implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_ALLIANCE_ID = "alliance_id";
  private Integer allianceId;

  public static final String JSON_PROPERTY_CORPORATION_ID = "corporation_id";
  private Integer corporationId;

  public static final String JSON_PROPERTY_ISK_DESTROYED = "isk_destroyed";
  private Float iskDestroyed;

  public static final String JSON_PROPERTY_SHIPS_KILLED = "ships_killed";
  private Integer shipsKilled;


  public GetWarsWarIdDefender allianceId(Integer allianceId) {
    
    this.allianceId = allianceId;
    return this;
  }

   /**
   * Alliance ID if and only if the defender is an alliance
   * @return allianceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Alliance ID if and only if the defender is an alliance")
  @JsonProperty(JSON_PROPERTY_ALLIANCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAllianceId() {
    return allianceId;
  }


  public void setAllianceId(Integer allianceId) {
    this.allianceId = allianceId;
  }


  public GetWarsWarIdDefender corporationId(Integer corporationId) {
    
    this.corporationId = corporationId;
    return this;
  }

   /**
   * Corporation ID if and only if the defender is a corporation
   * @return corporationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Corporation ID if and only if the defender is a corporation")
  @JsonProperty(JSON_PROPERTY_CORPORATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCorporationId() {
    return corporationId;
  }


  public void setCorporationId(Integer corporationId) {
    this.corporationId = corporationId;
  }


  public GetWarsWarIdDefender iskDestroyed(Float iskDestroyed) {
    
    this.iskDestroyed = iskDestroyed;
    return this;
  }

   /**
   * ISK value of ships the defender has killed
   * @return iskDestroyed
  **/
  @ApiModelProperty(required = true, value = "ISK value of ships the defender has killed")
  @JsonProperty(JSON_PROPERTY_ISK_DESTROYED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Float getIskDestroyed() {
    return iskDestroyed;
  }


  public void setIskDestroyed(Float iskDestroyed) {
    this.iskDestroyed = iskDestroyed;
  }


  public GetWarsWarIdDefender shipsKilled(Integer shipsKilled) {
    
    this.shipsKilled = shipsKilled;
    return this;
  }

   /**
   * The number of ships the defender has killed
   * @return shipsKilled
  **/
  @ApiModelProperty(required = true, value = "The number of ships the defender has killed")
  @JsonProperty(JSON_PROPERTY_SHIPS_KILLED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getShipsKilled() {
    return shipsKilled;
  }


  public void setShipsKilled(Integer shipsKilled) {
    this.shipsKilled = shipsKilled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetWarsWarIdDefender getWarsWarIdDefender = (GetWarsWarIdDefender) o;
    return Objects.equals(this.allianceId, getWarsWarIdDefender.allianceId) &&
        Objects.equals(this.corporationId, getWarsWarIdDefender.corporationId) &&
        Objects.equals(this.iskDestroyed, getWarsWarIdDefender.iskDestroyed) &&
        Objects.equals(this.shipsKilled, getWarsWarIdDefender.shipsKilled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allianceId, corporationId, iskDestroyed, shipsKilled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetWarsWarIdDefender {\n");
    sb.append("    allianceId: ").append(toIndentedString(allianceId)).append("\n");
    sb.append("    corporationId: ").append(toIndentedString(corporationId)).append("\n");
    sb.append("    iskDestroyed: ").append(toIndentedString(iskDestroyed)).append("\n");
    sb.append("    shipsKilled: ").append(toIndentedString(shipsKilled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

