/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.3.8
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * invitation object
 */
@ApiModel(description = "invitation object")
@JsonPropertyOrder({
  PostFleetsFleetIdMembersInvitation.JSON_PROPERTY_CHARACTER_ID,
  PostFleetsFleetIdMembersInvitation.JSON_PROPERTY_ROLE,
  PostFleetsFleetIdMembersInvitation.JSON_PROPERTY_SQUAD_ID,
  PostFleetsFleetIdMembersInvitation.JSON_PROPERTY_WING_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-06-04T13:00:04.672Z[Etc/UTC]")
public class PostFleetsFleetIdMembersInvitation implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CHARACTER_ID = "character_id";
  private Integer characterId;

  /**
   * If a character is invited with the &#x60;fleet_commander&#x60; role, neither &#x60;wing_id&#x60; or &#x60;squad_id&#x60; should be specified. If a character is invited with the &#x60;wing_commander&#x60; role, only &#x60;wing_id&#x60; should be specified. If a character is invited with the &#x60;squad_commander&#x60; role, both &#x60;wing_id&#x60; and &#x60;squad_id&#x60; should be specified. If a character is invited with the &#x60;squad_member&#x60; role, &#x60;wing_id&#x60; and &#x60;squad_id&#x60; should either both be specified or not specified at all. If they aren’t specified, the invited character will join any squad with available positions.
   */
  public enum RoleEnum {
    FLEET_COMMANDER("fleet_commander"),
    
    WING_COMMANDER("wing_commander"),
    
    SQUAD_COMMANDER("squad_commander"),
    
    SQUAD_MEMBER("squad_member");

    private String value;

    RoleEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RoleEnum fromValue(String value) {
      for (RoleEnum b : RoleEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ROLE = "role";
  private RoleEnum role;

  public static final String JSON_PROPERTY_SQUAD_ID = "squad_id";
  private Long squadId;

  public static final String JSON_PROPERTY_WING_ID = "wing_id";
  private Long wingId;


  public PostFleetsFleetIdMembersInvitation characterId(Integer characterId) {
    
    this.characterId = characterId;
    return this;
  }

   /**
   * The character you want to invite
   * @return characterId
  **/
  @ApiModelProperty(required = true, value = "The character you want to invite")
  @JsonProperty(JSON_PROPERTY_CHARACTER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getCharacterId() {
    return characterId;
  }


  public void setCharacterId(Integer characterId) {
    this.characterId = characterId;
  }


  public PostFleetsFleetIdMembersInvitation role(RoleEnum role) {
    
    this.role = role;
    return this;
  }

   /**
   * If a character is invited with the &#x60;fleet_commander&#x60; role, neither &#x60;wing_id&#x60; or &#x60;squad_id&#x60; should be specified. If a character is invited with the &#x60;wing_commander&#x60; role, only &#x60;wing_id&#x60; should be specified. If a character is invited with the &#x60;squad_commander&#x60; role, both &#x60;wing_id&#x60; and &#x60;squad_id&#x60; should be specified. If a character is invited with the &#x60;squad_member&#x60; role, &#x60;wing_id&#x60; and &#x60;squad_id&#x60; should either both be specified or not specified at all. If they aren’t specified, the invited character will join any squad with available positions.
   * @return role
  **/
  @ApiModelProperty(required = true, value = "If a character is invited with the `fleet_commander` role, neither `wing_id` or `squad_id` should be specified. If a character is invited with the `wing_commander` role, only `wing_id` should be specified. If a character is invited with the `squad_commander` role, both `wing_id` and `squad_id` should be specified. If a character is invited with the `squad_member` role, `wing_id` and `squad_id` should either both be specified or not specified at all. If they aren’t specified, the invited character will join any squad with available positions.")
  @JsonProperty(JSON_PROPERTY_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RoleEnum getRole() {
    return role;
  }


  public void setRole(RoleEnum role) {
    this.role = role;
  }


  public PostFleetsFleetIdMembersInvitation squadId(Long squadId) {
    
    this.squadId = squadId;
    return this;
  }

   /**
   * squad_id integer
   * minimum: 0
   * @return squadId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "squad_id integer")
  @JsonProperty(JSON_PROPERTY_SQUAD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSquadId() {
    return squadId;
  }


  public void setSquadId(Long squadId) {
    this.squadId = squadId;
  }


  public PostFleetsFleetIdMembersInvitation wingId(Long wingId) {
    
    this.wingId = wingId;
    return this;
  }

   /**
   * wing_id integer
   * minimum: 0
   * @return wingId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "wing_id integer")
  @JsonProperty(JSON_PROPERTY_WING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWingId() {
    return wingId;
  }


  public void setWingId(Long wingId) {
    this.wingId = wingId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostFleetsFleetIdMembersInvitation postFleetsFleetIdMembersInvitation = (PostFleetsFleetIdMembersInvitation) o;
    return Objects.equals(this.characterId, postFleetsFleetIdMembersInvitation.characterId) &&
        Objects.equals(this.role, postFleetsFleetIdMembersInvitation.role) &&
        Objects.equals(this.squadId, postFleetsFleetIdMembersInvitation.squadId) &&
        Objects.equals(this.wingId, postFleetsFleetIdMembersInvitation.wingId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(characterId, role, squadId, wingId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostFleetsFleetIdMembersInvitation {\n");
    sb.append("    characterId: ").append(toIndentedString(characterId)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    squadId: ").append(toIndentedString(squadId)).append("\n");
    sb.append("    wingId: ").append(toIndentedString(wingId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

